proxysql-admin sanity check

diff --git a/proxysql-admin b/proxysql-admin
--- a/proxysql-admin
+++ b/proxysql-admin
@@ -18,7 +18,7 @@
 # 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.
 
 # Make sure only root can run this script
-if [ $(id -u) -ne 0 ]; then
+if [ "$(id -u)" -ne 0 ]; then
   echo "ERROR: This script must be run as root!" 1>&2
   exit 1
 fi
@@ -68,7 +68,7 @@ if ! getopt --test
   go_out="$(getopt --options=edv --longoptions=config-file:,proxysql-username:,proxysql-password::,proxysql-hostname:,proxysql-port:,cluster-username:,cluster-password::,cluster-hostname:,cluster-port:,monitor-username:,monitor-password:,cluster-app-username:,cluster-app-password:,node-check-interval:,quick-demo,mode:,write-node:,enable,disable,adduser,version,help \
   --name="$(basename "$0")" -- "$@")"
   test $? -eq 0 || exit 1
-  eval set -- $go_out
+  eval set -- "$go_out"
 fi
 
 if [[ $go_out == " --" ]];then
@@ -80,6 +80,7 @@ if ! echo "$go_out" | grep -q 'config-file'; then
   if ! echo "$go_out" | grep -q 'quick-demo'; then
     # Reading default variables from default configuration file location.
     if [ -e "/etc/proxysql-admin.cnf" ]; then
+      # Loading default configuration from /etc/proxysql-admin.cnf
       source /etc/proxysql-admin.cnf
       CONFIG_FILE="/etc/proxysql-admin.cnf"
     else
@@ -100,6 +101,7 @@ do
         exit 1
       fi
       if [ -e "${CONFIG_FILE}" ]; then
+        # Loading configuration from ${CONFIG_FILE}
         source "${CONFIG_FILE}"
       else
         echo "ERROR: The configuration file ${CONFIG_FILE} specified by --config-file does not exist. Terminating."
@@ -201,7 +203,7 @@ do
     --mode )
     MODE="$2"
     shift 2
-    if [ $MODE != "loadbal" -a $MODE != "singlewrite" ]; then
+    if [ "$MODE" != "loadbal" ] && [ "$MODE" != "singlewrite" ]; then
       echo "ERROR: Invalid --mode passed:"
       echo "  Please choose any of these modes: loadbal, singlewrite"
       exit 1
@@ -231,7 +233,7 @@ if [ ! -z "$QUICK_DEMO" ]; then
   echo -e "\nThis script will assist with configuring ProxySQL (currently only Percona XtraDB cluster in combination with ProxySQL is supported)"
   echo -e "\nYou have selected the dry test run mode. WARNING: This will create a test user (with all privileges) in the Percona XtraDB Cluster & ProxySQL installations.\n"
   echo -e "You may want to delete this user after you complete your testing!\n"
-  read -p "Would you like to proceed with '--quick-demo' [y/n] ? " check_param
+  read -r -p "Would you like to proceed with '--quick-demo' [y/n] ? " check_param
   case $check_param in
     y|Y)
       echo -e "\nSetting up proxysql test configuration!\n"
@@ -247,7 +249,7 @@ if [ ! -z "$QUICK_DEMO" ]; then
   esac
 fi
 
-if [[ ! -e `which mysql 2> /dev/null` ]] ;then
+if [[ ! -e $(which mysql 2> /dev/null) ]] ;then
   echo "The mysql client was not found, please install the mysql client package using your OS packaging manager!"
   exit 1
 fi
@@ -282,7 +284,7 @@ if [ -z "$QUICK_DEMO" ]; then
     CLUSTER_PORT="localhost"
   fi
 else
-  read -p "Do you want to use the default ProxySQL credentials (admin:admin:6032:127.0.0.1) [y/n] ? " check_param
+  read -r -p "Do you want to use the default ProxySQL credentials (admin:admin:6032:127.0.0.1) [y/n] ? " check_param
   case $check_param in
     y|Y)
       PROXYSQL_USERNAME="admin"
@@ -307,7 +309,7 @@ else
     ;;
   esac
 
-  read -p "Do you want to use the default Percona XtraDB Cluster credentials (root::3306:127.0.0.1) [y/n] ? " check_param
+  read -r -p "Do you want to use the default Percona XtraDB Cluster credentials (root::3306:127.0.0.1) [y/n] ? " check_param
   case $check_param in
     y|Y)
       CLUSTER_USERNAME="root"
@@ -344,7 +346,7 @@ fi
 if [[ -z "$MODE" ]]; then
   MODE="singlewrite"
 else
-  if [ $MODE != "loadbal" -a $MODE != "singlewrite" ]; then
+  if [ "$MODE" != "loadbal" ] && [ "$MODE" != "singlewrite" ]; then
     echo "ERROR: Invalid --mode passed:"
     echo "  Please choose any of these modes: loadbal, singlewrite"
     exit 1
@@ -355,23 +357,23 @@ if [ $MODE == "loadbal" ]; then
   WRITE_HOSTGROUP_ID=10
   READ_HOSTGROUP_ID=10
   if [ -e "${CONFIG_FILE}" ]; then
-    sudo sed -i "0,/^[ \t]*export MODE[ \t]*=.*$/s|^[ \t]*export MODE[ \t]*=.*$|export MODE=\"loadbal\"|" ${CONFIG_FILE}
+    sudo sed -i "0,/^[ \t]*export MODE[ \t]*=.*$/s|^[ \t]*export MODE[ \t]*=.*$|export MODE=\"loadbal\"|" "${CONFIG_FILE}"
   fi
 elif [ $MODE == "singlewrite" ]; then
   WRITE_HOSTGROUP_ID=10
   READ_HOSTGROUP_ID=11
   if [ -e "${CONFIG_FILE}" ]; then
-    sudo sed -i "0,/^[ \t]*export MODE[ \t]*=.*$/s|^[ \t]*export MODE[ \t]*=.*$|export MODE=\"singlewrite\"|" ${CONFIG_FILE}
+    sudo sed -i "0,/^[ \t]*export MODE[ \t]*=.*$/s|^[ \t]*export MODE[ \t]*=.*$|export MODE=\"singlewrite\"|" "${CONFIG_FILE}"
   fi
 fi
 
-PIDFILE=/tmp/cluster-proxysql-monitor.pid
+export PIDFILE="/tmp/cluster-proxysql-monitor.pid"
 
 proxysql_exec() {
   query=$1
   args=$2
   printf "[client]\nuser=${PROXYSQL_USERNAME}\npassword=${PROXYSQL_PASSWORD}\nhost=${PROXYSQL_HOSTNAME}\nport=${PROXYSQL_PORT}\n" | \
-      mysql --defaults-file=/dev/stdin --protocol=tcp -${args}e  "${query}" 2>/dev/null
+      mysql --defaults-file=/dev/stdin --protocol=tcp -"${args}"e  "${query}" 2>/dev/null
 }
 
 mysql_exec() {
@@ -401,7 +403,7 @@ cluster_connection_check(){
 check_cmd(){
   MPID=$1
   ERROR_MSG=$2
-  if [ ${MPID} -ne 0 ]; then echo -e "\nERROR: $ERROR_MSG. Terminating!"; exit 1; fi
+  if [ "${MPID}" -ne 0 ]; then echo -e "\nERROR: $ERROR_MSG. Terminating!"; exit 1; fi
 }
 
 check_proxysql(){
@@ -415,9 +417,9 @@ user_input_check(){
   USER_CATEGORY=$1
   USER_DESCRIPTION=$2
   HOSTGROUP_ID=$3
-  USERNAME=`eval "echo \\$${USER_CATEGORY}_USERNAME"`
-  PASSWORD=`eval "echo \\$${USER_CATEGORY}_PASSWORD"`
-  if [[ -z $USERNAME ]]; then
+  USERNAME=$(eval "echo \$${USER_CATEGORY}_USERNAME")
+  PASSWORD=$(eval "echo \$${USER_CATEGORY}_PASSWORD")
+  if [[ -z "$USERNAME" ]]; then
     read -r -p "Enter ${USER_DESCRIPTION}name : " ${USER_CATEGORY}_USERNAME
     while [[ -z "${USER_CATEGORY}_USERNAME" ]]
     do
@@ -426,7 +428,7 @@ user_input_check(){
     done
   else
     if [ -z "$QUICK_DEMO" ]; then
-      echo -e "${USER_DESCRIPTION}name as per command line/config-file is ${BD}`eval "echo \\$${USER_CATEGORY}_USERNAME"`${NBD}"
+      echo -e "${USER_DESCRIPTION}name as per command line/config-file is ${BD}$(eval "echo \$${USER_CATEGORY}_USERNAME")${NBD}"
     fi
   fi
   if [[ -z $PASSWORD ]]; then
@@ -438,10 +440,10 @@ user_input_check(){
       done
     fi
   fi
-  USERNAME=`eval "echo \\$${USER_CATEGORY}_USERNAME"`
-  PASSWORD=`eval "echo \\$${USER_CATEGORY}_PASSWORD"`
+  USERNAME=$(eval "echo \$${USER_CATEGORY}_USERNAME")
+  PASSWORD=$(eval "echo \$${USER_CATEGORY}_PASSWORD")
   if [ "$USER_CATEGORY" != "MONITOR" ]; then
-    check_user=`mysql_exec "SELECT user,host FROM mysql.user where user='$USERNAME' and host='$USER_HOST_RANGE';"`
+    check_user=$(mysql_exec "SELECT user,host FROM mysql.user where user='$USERNAME' and host='$USER_HOST_RANGE';")
     if [[ -z "$check_user" ]]; then
       mysql_exec "CREATE USER $USERNAME@'$USER_HOST_RANGE' IDENTIFIED BY '$PASSWORD';"
       check_cmd $? "Failed to add Percona XtraDB Cluster application user: '$USERNAME'. Please check '$CLUSTER_USERNAME'@'$CLUSTER_HOSTNAME' has proper permission to create montioring user"
@@ -458,7 +460,7 @@ user_input_check(){
         echo -e "\nPercona XtraDB Cluster application user '${BD}$USERNAME'@'$USER_HOST_RANGE${NBD}' has been added with ${BD}ALL${NBD} privileges, ${BD}this user is created for testing purposes${NBD}"
       fi
     else
-      check_user=`proxysql_exec "SELECT username FROM mysql_users where username='$USERNAME'"`
+      check_user=$(proxysql_exec "SELECT username FROM mysql_users where username='$USERNAME'")
       if [[ -z "$check_user" ]]; then
         echo -e "\nApplication user '${BD}${USERNAME}'@'$USER_HOST_RANGE${NBD}' already present in Percona XtraDB Cluster."
         proxysql_exec "INSERT INTO mysql_users (username,password,active,default_hostgroup) values ('$USERNAME','$PASSWORD',1,$HOSTGROUP_ID);LOAD MYSQL USERS TO RUNTIME;SAVE MYSQL USERS FROM RUNTIME;SAVE MYSQL USERS TO DISK;"
@@ -513,7 +515,7 @@ enable_proxysql(){
   echo -e "\nConfiguring ProxySQL monitoring user.."
   user_input_check MONITOR "ProxySQL monitor user"
 
-  check_user=`mysql_exec "SELECT user,host FROM mysql.user where user='$MONITOR_USERNAME' and host='$USER_HOST_RANGE';"`
+  check_user=$(mysql_exec "SELECT user,host FROM mysql.user where user='$MONITOR_USERNAME' and host='$USER_HOST_RANGE';")
   if [[ -z "$check_user" ]]; then
     mysql_exec "CREATE USER $MONITOR_USERNAME@'$USER_HOST_RANGE' IDENTIFIED BY '$MONITOR_PASSWORD';"
     check_cmd $?  "Failed to create the ProxySQL monitoring user. Please check '$CLUSTER_USERNAME'@'$CLUSTER_HOSTNAME' has proper permission to create montioring user"
@@ -553,10 +555,10 @@ enable_proxysql(){
   echo -e "\nAdding the Percona XtraDB Cluster server nodes to ProxySQL"
   if [ $MODE == "loadbal" ]; then
     proxysql_exec "DELETE FROM mysql_servers WHERE hostgroup_id=$WRITE_HOSTGROUP_ID"
-    wsrep_address=(`mysql_exec "show status like 'wsrep_incoming_addresses'" | awk '{print $2}' | sed 's|,| |g'`)
+    wsrep_address=($(mysql_exec "show status like 'wsrep_incoming_addresses'" | awk '{print $2}' | sed 's|,| |g'))
     for i in "${wsrep_address[@]}"; do	
-      ws_ip=$(echo $i | cut -d':' -f1)
-      ws_port=$(echo $i | cut -d':' -f2)
+      ws_ip=$(echo "$i" | cut -d':' -f1)
+      ws_port=$(echo "$i" | cut -d':' -f2)
       proxysql_exec "INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight,comment) VALUES ('$ws_ip',$WRITE_HOSTGROUP_ID,$ws_port,1000,'READWRITE');"
       check_cmd $? "Failed to add the Percona XtraDB Cluster server node $ws_ip:$ws_port. Please check username, password and other options for connecting to ProxySQL database"
     done
@@ -566,12 +568,12 @@ enable_proxysql(){
     proxysql_exec "DELETE FROM mysql_servers WHERE hostgroup_id in ($WRITE_HOSTGROUP_ID,$READ_HOSTGROUP_ID)"
     proxysql_exec "DELETE FROM mysql_query_rules WHERE destination_hostgroup in ($WRITE_HOSTGROUP_ID,$READ_HOSTGROUP_ID)"
     if [ -z "$QUICK_DEMO" ]; then
-      if [ -z $WRITE_NODE ]; then
-        writer_ws_ip=(`mysql_exec "show variables like 'wsrep_provider_options'" | grep -o -P '(?<=base_host =).*(?=; base_port)' | xargs`)
+      if [ -z "$WRITE_NODE" ]; then
+        writer_ws_ip=$(mysql_exec "show variables like 'wsrep_provider_options'" | grep -o -P '(?<=base_host =).*(?=; base_port)' | xargs)
         writer_ws_port=$CLUSTER_PORT
       else
-        writer_ws_ip=$(echo $WRITE_NODE | awk -F':' '{print $1}')
-        writer_ws_port=$(echo $WRITE_NODE | awk -F':' '{print $2}')
+        writer_ws_ip=$(echo "$WRITE_NODE" | awk -F':' '{print $1}')
+        writer_ws_port=$(echo "$WRITE_NODE" | awk -F':' '{print $2}')
         if [ -z "$writer_ws_port" ];then
           writer_ws_port=3306
         fi
@@ -584,21 +586,21 @@ enable_proxysql(){
         fi
       fi
     else
-      writer_ws_ip=(`mysql_exec "show variables like 'wsrep_provider_options'" | grep -o -P '(?<=base_host =).*(?=; base_port)' | xargs`)
+      writer_ws_ip=$(mysql_exec "show variables like 'wsrep_provider_options'" | grep -o -P '(?<=base_host =).*(?=; base_port)' | xargs)
       writer_ws_port=$CLUSTER_PORT
     fi
     proxysql_exec "DELETE FROM mysql_servers WHERE hostgroup_id=$WRITE_HOSTGROUP_ID"
-    wsrep_address=(`mysql_exec "show status like 'wsrep_incoming_addresses'" | awk '{print $2}' | sed 's|,| |g'`)
-    if [[ ${wsrep_address[@]} != *"$writer_ws_ip:$writer_ws_port"* ]]; then
-      echo -e "\nERROR: Writer node cluster address($writer_ws_ip:$writer_ws_port) does not exist in WSREP incoming address(${wsrep_address[@]})."
+    wsrep_address=($(mysql_exec "show status like 'wsrep_incoming_addresses'" | awk '{print $2}' | sed 's|,| |g'))
+    if [[ ${wsrep_address[*]} != *"$writer_ws_ip:$writer_ws_port"* ]]; then
+      echo -e "\nERROR: Writer node cluster address($writer_ws_ip:$writer_ws_port) does not exist in WSREP incoming address(${wsrep_address[*]})."
       echo -e "Different wsrep incoming and cluster IP addresses are not supported by proxysql-admin at this time"
       echo -e "Please configure ProxySQL manually.. Terminating!"
       exit 1
     fi
     for i in "${wsrep_address[@]}"; do	
-      ws_ip=$(echo $i | cut -d':' -f1)
-      ws_port=$(echo $i | cut -d':' -f2)
-      if [ "$ws_ip" == "$writer_ws_ip" -a "$ws_port" == "$writer_ws_port" ]; then
+      ws_ip=$(echo "$i" | cut -d':' -f1)
+      ws_port=$(echo "$i" | cut -d':' -f2)
+      if [ "$ws_ip" == "$writer_ws_ip" ] && [ "$ws_port" == "$writer_ws_port" ]; then
         proxysql_exec "INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight,comment) VALUES ('$writer_ws_ip',$WRITE_HOSTGROUP_ID,$writer_ws_port,1000000,'WRITE');"
         check_cmd $? "Failed to add the Percona XtraDB Cluster server node $writer_ws_ip:$writer_ws_port. Please check username, password and other options for connecting to ProxySQL database"
         echo -e "\nWrite node info"
@@ -668,12 +670,12 @@ adduser(){
     read -r -s -p  "No input entered. Enter the Percona XtraDB Cluster application user password: " CLUSTER_APP_WRITE_PASSWORD
   done
 
-  check_user=`proxysql_exec "SELECT username FROM mysql_users where username='$CLUSTER_APP_WRITE_USERNAME'"`
+  check_user=$(proxysql_exec "SELECT username FROM mysql_users where username='$CLUSTER_APP_WRITE_USERNAME'")
   if [[ -z "$check_user" ]]; then
-    check_cluster_user=`mysql_exec "SELECT user,host FROM mysql.user where user='$CLUSTER_APP_WRITE_USERNAME'"`
+    check_cluster_user=$(mysql_exec "SELECT user,host FROM mysql.user where user='$CLUSTER_APP_WRITE_USERNAME'")
     if [[ -z "$check_cluster_user" ]]; then
       echo -e "\n\n"
-      read -p "The application user '$CLUSTER_APP_WRITE_USERNAME' does not exist in Percona XtraDB Cluster. Would you like to proceed [y/n] ? " check_param
+      read -r -p "The application user '$CLUSTER_APP_WRITE_USERNAME' does not exist in Percona XtraDB Cluster. Would you like to proceed [y/n] ? " check_param
       case $check_param in
         y|Y)
           proxysql_exec "INSERT INTO mysql_users (username,password,active,default_hostgroup) values ('$CLUSTER_APP_WRITE_USERNAME','$CLUSTER_APP_WRITE_PASSWORD',1,$WRITE_HOSTGROUP_ID);LOAD MYSQL USERS TO RUNTIME;SAVE MYSQL USERS FROM RUNTIME;SAVE MYSQL USERS TO DISK;"
@@ -698,7 +700,7 @@ adduser(){
   fi
 }
 
-if [ "$ENABLE" == 1 -o "$DISABLE" == 1 -o "$ADDUSER" == 1 ]; then
+if [ "$ENABLE" == 1 ] || [ "$DISABLE" == 1 ] || [ "$ADDUSER" == 1 ]; then
   if [ "$ENABLE" == 1 ];then
     if [ -z "$QUICK_DEMO" ]; then
       echo -e "\nThis script will assist with configuring ProxySQL (currently only Percona XtraDB cluster in combination with ProxySQL is supported)"
@@ -706,7 +708,7 @@ if [ "$ENABLE" == 1 -o "$DISABLE" == 1 -o "$ADDUSER" == 1 ]; then
     echo -e "\nProxySQL read/write configuration mode is ${BD}$MODE${NBD}"
     enable_proxysql
     echo -e "\nProxySQL configuration completed!\n"
-    PROXYSQL_CLIENT_PORT=`proxysql_exec "SELECT * FROM runtime_global_variables WHERE variable_name='mysql-interfaces'" | awk '{print $2}' | grep -o -P '(?<=:).*(?=;)'`
+    PROXYSQL_CLIENT_PORT=$(proxysql_exec "SELECT * FROM runtime_global_variables WHERE variable_name='mysql-interfaces'" | awk '{print $2}' | grep -o -P '(?<=:).*(?=;)')
     echo -e "ProxySQL has been successfully configured to use with Percona XtraDB Cluster\n"
     echo -e "You can use the following login credentials to connect your application through ProxySQL\n"
     if [ -z "$QUICK_DEMO" ]; then
@@ -727,5 +729,3 @@ else
   echo "Usage: proxysql-admin <user credentials> {enable|disable}"
   usage
 fi
-
-
