Updated proxysql_node_monitor to handle slave connection message properly

diff --git a/proxysql_node_monitor b/proxysql_node_monitor
--- a/proxysql_node_monitor
+++ b/proxysql_node_monitor
@@ -34,8 +34,12 @@ fi
 check_cmd(){
   MPID=$1
   ERROR_MSG=$2
+  ERROR_INFO=$3
   if [ ${MPID} -ne 0 ]; then 
     echo "`date` WARNING: $ERROR_MSG." >> $ERR_FILE
+    if [[ ! -z  $ERROR_INFO ]]; then
+      echo "`date` $ERROR_INFO." >> $ERR_FILE
+    fi
   fi
 }
 
@@ -56,8 +60,9 @@ set_slave_status() {
   # The ws_ip and ws_port variables are used and must be set before calling this function
   if [ $debug -eq 1 ];then echo "`date` DEBUG START set_slave_status" >> $ERR_FILE;fi
   # This function will get and return a status of a slave node, 4=GOOD, 2=BEHIND, 0=OTHER
-  SLAVE_STATUS=$(printf "[client]\nuser=${CLUSTER_USERNAME}\npassword=${CLUSTER_PASSWORD}\nhost=${ws_ip}\nport=${ws_port}\n" | mysql --defaults-file=/dev/stdin --protocol=tcp -Bse 'SHOW SLAVE STATUS\G' 2>/dev/null | sed 's/ //g')
-  check_cmd $? "Cannot get staus from the slave $ws_ip:$ws_port, Please check cluster login credentials"
+  SLAVE_STATUS=$(printf "[client]\nuser=${CLUSTER_USERNAME}\npassword=${CLUSTER_PASSWORD}\nhost=${ws_ip}\nport=${ws_port}\n" | mysql --defaults-file=/dev/stdin --protocol=tcp -Bse 'SHOW SLAVE STATUS\G' 2>/var/lib/proxysql/proxysql_admin_error_info)
+  check_cmd $? "Cannot get staus from the slave $ws_ip:$ws_port, Please check cluster login credentials" "`cat /var/lib/proxysql/proxysql_admin_error_info`"
+  SLAVE_STATUS=$(echo "$SLAVE_STATUS" | sed 's/ //g')
   echo "$SLAVE_STATUS" | grep "^Master_Host:" >/dev/null
   if [ $? -ne 0 ];then
     # No status was found, this is not replicating
