Fixed BLD-612 - Call proxysql_node_monitor script inside proxysql_galera_checker script.

diff --git a/proxysql_galera_checker b/proxysql_galera_checker
--- a/proxysql_galera_checker
+++ b/proxysql_galera_checker
@@ -49,6 +49,15 @@ NUMBER_WRITERS="${3:-0}"
 WRITER_IS_READER="${4:-1}"
 ERR_FILE="${5:-/dev/null}"
 
+#Running proxysql_node_monitor script.
+if [ ! -f /usr/bin/proxysql_node_monitor ] ;then
+  echo "`date` ERROR! Could not run /usr/bin/proxysql_node_monitor. Monitoring script does not exists in default location. Terminating" >> ${ERR_FILE}
+  exit 1  
+else
+  /usr/bin/proxysql_node_monitor $HOSTGROUP_WRITER_ID $HOSTGROUP_READER_ID /var/lib/proxysql/proxysql_node_monitor.log
+fi
+
+
 proxysql_exec() {
   local query="$1"
   printf "%s\n" \
