Small updates

diff --git a/proxysql-admin b/proxysql-admin
--- a/proxysql-admin
+++ b/proxysql-admin
@@ -3,6 +3,13 @@
 # Version 1.0
 ###############################################################################################
 
+
+# Make sure only root can run this script
+if [ $(id -u) -ne 0 ]; then
+  echo "ERROR: This script must be run as root!" 1>&2
+  exit
+fi
+
 # Dispay script usage details
 usage () {
   echo "Usage: [ options ]"
