Added safety check to verify  is writable

diff --git a/proxysql-admin b/proxysql-admin
--- a/proxysql-admin
+++ b/proxysql-admin
@@ -391,6 +391,14 @@ fi
 if [ -z $WRITE_HOSTGROUP_ID ];then WRITE_HOSTGROUP_ID=10;fi
 if [ -z $READ_HOSTGROUP_ID ];then READ_HOSTGROUP_ID=11;fi
 
+# We don't use need the correct mode in ${CONFIG_FILE} anymore 
+# We are using ${PROXYSQL_DATADIR}/${CLUSTER_NAME}_mode
+# Adding this check just for safety to avoid below sed to fail
+if [[ ! -w ${CONFIG_FILE} ]]; then
+  echo "ERROR: cannot write to file ${CONFIG_FILE}"
+  exit 1
+fi
+
 if [ $MODE == "loadbal" ]; then
   SLAVEREAD_HOSTGROUP_ID=$READ_HOSTGROUP_ID
   READ_HOSTGROUP_ID=$WRITE_HOSTGROUP_ID
