PSQLADM-32 : Updated proxysql-admin scripts to configure multiple clusters in proxysql

diff --git a/proxysql-admin b/proxysql-admin
--- a/proxysql-admin
+++ b/proxysql-admin
@@ -249,7 +249,7 @@ do
     ENABLE=1
     ;;
     -v | --version )
-      echo "proxysql-admin version 1.4.5"
+      echo "proxysql-admin version 1.4.6"
       exit 0
     ;;
     --help )
@@ -456,6 +456,10 @@ check_proxysql(){
   fi
 }
 
+CLUSTER_NAME=$(mysql_exec "select @@wsrep_cluster_name;")
+rm -rf ${PROXYSQL_DATADIR}/${CLUSTER_NAME}_mode
+echo "$MODE" > ${PROXYSQL_DATADIR}/${CLUSTER_NAME}_mode
+
 user_input_check(){
   USER_CATEGORY=$1
   USER_DESCRIPTION=$2
@@ -488,19 +492,26 @@ user_input_check(){
   if [ "$USER_CATEGORY" != "MONITOR" ]; then
     check_user=$(mysql_exec "SELECT user,host FROM mysql.user where user='$USERNAME' and host='$USER_HOST_RANGE';")
     if [[ -z "$check_user" ]]; then
-      mysql_exec "CREATE USER $USERNAME@'$USER_HOST_RANGE' IDENTIFIED BY '$PASSWORD';"
-      check_cmd $? "Failed to add Percona XtraDB Cluster application user: '$USERNAME'. Please check '$CLUSTER_USERNAME'@'$CLUSTER_HOSTNAME' has proper permission to create montioring user"
-      if [ ! -z "$QUICK_DEMO" ]; then
-        mysql_exec "GRANT ALL ON *.* to $USERNAME@'$USER_HOST_RANGE'"
-        check_cmd $? "$CLUSTER_USERNAME@'$CLUSTER_HOSTNAME' does not have the GRANT privilege required to assign the requested permissions"
-      fi
+      precheck_user=$(proxysql_exec "SELECT username FROM mysql_users where username='$USERNAME'")
+	  if [[ -z "$precheck_user" ]]; then  
+        mysql_exec "CREATE USER $USERNAME@'$USER_HOST_RANGE' IDENTIFIED BY '$PASSWORD';"
+        check_cmd $? "Failed to add Percona XtraDB Cluster application user: '$USERNAME'. Please check '$CLUSTER_USERNAME'@'$CLUSTER_HOSTNAME' has proper permission to create montioring user"
+        if [ ! -z "$QUICK_DEMO" ]; then
+          mysql_exec "GRANT ALL ON *.* to $USERNAME@'$USER_HOST_RANGE'"
+          check_cmd $? "$CLUSTER_USERNAME@'$CLUSTER_HOSTNAME' does not have the GRANT privilege required to assign the requested permissions"
+        fi
 
-      proxysql_exec "INSERT INTO mysql_users (username,password,active,default_hostgroup) values ('$USERNAME','$PASSWORD',1,$HOSTGROUP_ID);LOAD MYSQL USERS TO RUNTIME;SAVE MYSQL USERS FROM RUNTIME;SAVE MYSQL USERS TO DISK;"
-      check_cmd $? "Failed to add Percona XtraDB Cluster application user: '$USERNAME' in ProxySQL database. Please check username, password and other options for connecting to ProxySQL database"
-      if [ -z "$QUICK_DEMO" ]; then
-        echo -e "\nPercona XtraDB Cluster application user '${BD}$USERNAME'@'$USER_HOST_RANGE${NBD}' has been added with the USAGE privilege, please make sure to the grant appropriate privileges"
+        proxysql_exec "INSERT INTO mysql_users (username,password,active,default_hostgroup) values ('$USERNAME','$PASSWORD',1,$HOSTGROUP_ID);LOAD MYSQL USERS TO RUNTIME;SAVE MYSQL USERS FROM RUNTIME;SAVE MYSQL USERS TO DISK;"
+        check_cmd $? "Failed to add Percona XtraDB Cluster application user: '$USERNAME' in ProxySQL database. Please check username, password and other options for connecting to ProxySQL database"
+        if [ -z "$QUICK_DEMO" ]; then
+          echo -e "\nPercona XtraDB Cluster application user '${BD}$USERNAME'@'$USER_HOST_RANGE${NBD}' has been added with the USAGE privilege, please make sure to the grant appropriate privileges"
+        else
+          echo -e "\nPercona XtraDB Cluster application user '${BD}$USERNAME'@'$USER_HOST_RANGE${NBD}' has been added with ${BD}ALL${NBD} privileges, ${BD}this user is created for testing purposes${NBD}"
+        fi
       else
-        echo -e "\nPercona XtraDB Cluster application user '${BD}$USERNAME'@'$USER_HOST_RANGE${NBD}' has been added with ${BD}ALL${NBD} privileges, ${BD}this user is created for testing purposes${NBD}"
+        echo -e "\nERROR: The application user ${BD}$USERNAME${NBD} is already present in ProxySQL database. Terminating!"
+        echo -e " Note: ProxySQL do not allow duplicate username."
+        exit 1
       fi
     else
       check_user=$(proxysql_exec "SELECT username FROM mysql_users where username='$USERNAME'")
@@ -509,7 +520,9 @@ user_input_check(){
         proxysql_exec "INSERT INTO mysql_users (username,password,active,default_hostgroup) values ('$USERNAME','$PASSWORD',1,$HOSTGROUP_ID);LOAD MYSQL USERS TO RUNTIME;SAVE MYSQL USERS FROM RUNTIME;SAVE MYSQL USERS TO DISK;"
         check_cmd $? "Failed to add Percona XtraDB Cluster application user: '$USERNAME' in ProxySQL database. Please check username, password and other options for connecting to ProxySQL database"
       else
-        echo -e "\nThe application user '${BD}${USERNAME}'@'$USER_HOST_RANGE${NBD}' is already present in Percona XtraDB Cluster and ProxySQL database."
+        echo -e "\nERROR: The application user ${BD}$USERNAME${NBD} is already present in ProxySQL database. Terminating!"
+        echo -e " Note: ProxySQL do not allow duplicate username."
+        exit 1
       fi
     fi
   fi
@@ -566,6 +579,11 @@ enable_proxysql(){
 
   cluster_connection_check
 
+  check_hgs=$(proxysql_exec "SELECT hostgroup_id FROM mysql_servers where hostgroup_id in ($READ_HOSTGROUP_ID,$WRITE_HOSTGROUP_ID)")
+  if [[ ! -z "$check_hgs" ]]; then
+    echo -e "\nERROR: READ/WRITE hostgroups($READ_HOSTGROUP_ID,$WRITE_HOSTGROUP_ID) are already present in ProxySQL database. Terminating!"
+    exit 1
+  fi
   CLUSTER_NETWORK=$(mysql_exec "show status like 'wsrep_incoming_addresses'" | awk '{print $2}' | cut -d'.' -f1)
   if [[ "$CLUSTER_NETWORK" =~ ^[0-9]+$ ]]; then 
     USER_HOST_RANGE="$CLUSTER_NETWORK.%"
@@ -742,22 +760,16 @@ enable_proxysql(){
 
   # Adding Percona XtraDB Cluster monitoring scripts
   # Adding proxysql galera check scheduler
-  proxysql_exec "DELETE FROM SCHEDULER WHERE ID=10;"
+  proxysql_exec "DELETE FROM SCHEDULER WHERE COMMENT='$CLUSTER_NAME';"
   check_cmd $? "Failed to delete the Percona XtraDB Cluster nodes from ProxySQL. Please check username, password and other options for connecting to ProxySQL database"
   if [ $MODE == "singlewrite" ]; then
     NUMBER_WRITERS=1
   else
     NUMBER_WRITERS=0
   fi
-  proxysql_exec "INSERT  INTO SCHEDULER (id,active,interval_ms,filename,arg1,arg2,arg3,arg4,arg5) VALUES (10,1,$NODE_CHECK_INTERVAL,'$PROXYSQL_GALERA_CHECK',$WRITE_HOSTGROUP_ID,$READ_HOSTGROUP_ID,$NUMBER_WRITERS,1,'$PROXYSQL_DATADIR/proxysql_galera_check.log');"
+  proxysql_exec "INSERT  INTO SCHEDULER (active,interval_ms,filename,arg1,arg2,arg3,arg4,arg5,comment) VALUES (1,$NODE_CHECK_INTERVAL,'$PROXYSQL_GALERA_CHECK',$WRITE_HOSTGROUP_ID,$READ_HOSTGROUP_ID,$NUMBER_WRITERS,1,'$PROXYSQL_DATADIR/${CLUSTER_NAME}_proxysql_galera_check.log','$CLUSTER_NAME');"
   check_cmd $? "Failed to add the Percona XtraDB Cluster monitoring scheduler in ProxySQL. Please check username, password and other options for connecting to ProxySQL database"
-
-  # Adding Percona XtraDB Cluster membership checking scheduler
-  #proxysql_exec "DELETE FROM SCHEDULER WHERE ID=11;"
-  #check_cmd $?
-  #proxysql_exec "INSERT  INTO SCHEDULER (id,active,interval_ms,filename,arg1,arg2,arg3) VALUES (11,1,5000,'$PROXYSQL_NODE_MONITOR',$WRITE_HOSTGROUP_ID,$READ_HOSTGROUP_ID,'$PROXYSQL_DATADIR/proxysql_node_monitor.log');"
-  #check_cmd $? "Failed to add the Percona XtraDB Cluster membership checking scheduler in ProxySQL"
-
+  
   proxysql_exec "LOAD SCHEDULER TO RUNTIME;SAVE SCHEDULER TO DISK;"
 }
 
@@ -771,7 +783,7 @@ disable_proxysql(){
   proxysql_exec "DELETE FROM mysql_servers WHERE hostgroup_id in ($WRITE_HOSTGROUP_ID,$READ_HOSTGROUP_ID);"
   check_cmd $? "Failed to delete the Percona XtraDB Cluster nodes from ProxySQL. Please check username, password and other options for connecting to ProxySQL database"
   echo "Removing scheduler script from ProxySQL database."
-  proxysql_exec "DELETE FROM SCHEDULER WHERE ID IN (10);"
+  proxysql_exec "DELETE FROM SCHEDULER WHERE COMMENT='$CLUSTER_NAME';"
   check_cmd $? "Failed to delete the Galera checker from ProxySQL. Please check username, password and other options for connecting to ProxySQL database"
   echo "Removing query rules from ProxySQL database if any."
   proxysql_exec "DELETE FROM mysql_query_rules WHERE destination_hostgroup in ($WRITE_HOSTGROUP_ID,$READ_HOSTGROUP_ID)"
diff --git a/proxysql_galera_checker b/proxysql_galera_checker
--- a/proxysql_galera_checker
+++ b/proxysql_galera_checker
@@ -36,8 +36,8 @@ Notes about the mysql_servers in ProxySQL:
                      will be changed to either ONLINE or OFFLINE_SOFT.
 
 
-When no nodes were found to be in wsrep_local_state=4 (SYNCED) for either 
-read or write nodes, then the script will try 5 times for each node to try 
+When no nodes were found to be in wsrep_local_state=4 (SYNCED) for either
+read or write nodes, then the script will try 5 times for each node to try
 to find nodes wsrep_local_state=4 (SYNCED) or wsrep_local_state=2 (DONOR/DESYNC)
 
 This is to avoid $0 to mark all nodes as OFFLINE_SOFT
@@ -56,15 +56,6 @@ RELOAD_CHECK_FILE="${PROXYSQL_DATADIR}/reload"
 
 echo "0" > ${RELOAD_CHECK_FILE}
 
-#Running proxysql_node_monitor script.
-if [ ! -f /usr/bin/proxysql_node_monitor ] ;then
-  echo "`date` ERROR! Could not run /usr/bin/proxysql_node_monitor. Monitoring script does not exists in default location. Terminating" >> ${ERR_FILE}
-  exit 1  
-else
-  /usr/bin/proxysql_node_monitor $HOSTGROUP_WRITER_ID $HOSTGROUP_READER_ID ${PROXYSQL_DATADIR}/proxysql_node_monitor.log
-fi
-
-
 proxysql_exec() {
   local query="$1"
   printf "%s\n" \
@@ -76,6 +67,7 @@ proxysql_exec() {
       | mysql --defaults-file=/dev/stdin --protocol=tcp -Nse "${query}"
 }
 
+CLUSTER_NAME=$(proxysql_exec "select comment from scheduler where arg1=$HOSTGROUP_WRITER_ID")
 #Timeout exists for instances where mysqld may be hung
 TIMEOUT=10
 
@@ -89,6 +81,14 @@ mysql_exec() {
       "port=${port}"  \
       | timeout $TIMEOUT mysql --defaults-file=/dev/stdin --protocol=tcp -nNE -e "${query}"
 }
+
+#Running proxysql_node_monitor script.
+if [ ! -f /usr/bin/proxysql_node_monitor ] ;then
+  echo "`date` ERROR! Could not run /usr/bin/proxysql_node_monitor. Monitoring script does not exists in default location. Terminating" >> ${ERR_FILE}
+  exit 1
+else
+  /usr/bin/proxysql_node_monitor $HOSTGROUP_WRITER_ID $HOSTGROUP_READER_ID ${PROXYSQL_DATADIR}/${CLUSTER_NAME}_proxysql_node_monitor.log
+fi
 
 if [ "$1" = '-h' -o "$1" = '--help'  -o -z "$1" ]
 then
@@ -130,7 +130,7 @@ if [ $WRITER_IS_READER -ne 0 -a $WRITER_IS_READER -ne 1 ]; then
 fi
 
 
-# print information prior to a run if ${ERR_FILE} is defined 
+# print information prior to a run if ${ERR_FILE} is defined
 echo "`date` ###### proxysql_galera_checker.sh SUMMARY ######" >> ${ERR_FILE}
 echo "`date` Hostgroup writers $HOSTGROUP_WRITER_ID" >> ${ERR_FILE}
 echo "`date` Hostgroup readers $HOSTGROUP_READER_ID" >> ${ERR_FILE}
@@ -280,13 +280,13 @@ if [ ${HOSTGROUP_READER_ID} -ne -1 ]; then
          reader.status,
          writer.status
   FROM mysql_servers as reader
-  LEFT JOIN mysql_servers as writer 
-    ON writer.hostgroup_id = $HOSTGROUP_WRITER_ID 
-    AND writer.hostname = reader.hostname 
+  LEFT JOIN mysql_servers as writer
+    ON writer.hostgroup_id = $HOSTGROUP_WRITER_ID
+    AND writer.hostname = reader.hostname
     AND writer.port = reader.port
   WHERE reader.hostgroup_id = $HOSTGROUP_READER_ID
     AND reader.status <> 'OFFLINE_HARD'
-	AND reader.comment <> 'SLAVEREAD'
+        AND reader.comment <> 'SLAVEREAD'
   ORDER BY writer.status ASC,
            reader.weight DESC,
            reader.hostname,
@@ -354,7 +354,7 @@ if [ ${HOSTGROUP_READER_ID} -ne -1 ]; then
           echo "`date` server $hostgroup:$server:$port is already ONLINE" >> ${ERR_FILE}
           OFFLINE_READERS_FOUND=$(( $OFFLINE_READERS_FOUND + 1 ))
         fi
-      
+
         # WSREP status OK, but node is not marked ONLINE
         if [ "${WSREP_STATUS}" = "4" -a "$stat" != "ONLINE" ] ; then
           change_server_status $HOSTGROUP_READER_ID "$server" $port "ONLINE" "changed state, making read node ONLINE"
@@ -369,7 +369,7 @@ if [ ${HOSTGROUP_READER_ID} -ne -1 ]; then
           echo "`date` server $hostgroup:$server:$port is $stat" >> ${ERR_FILE}
           OFFLINE_READERS_FOUND=$(( $OFFLINE_READERS_FOUND + 1 ))
         fi
-      
+
         # WSREP status OK, but node is not marked ONLINE
         if [ "${WSREP_STATUS}" = "4" -a "$stat" != "ONLINE" -a "${PXC_MAIN_MODE}" == "DISABLED" ] ; then
           change_server_status $HOSTGROUP_READER_ID "$server" $port "ONLINE" "changed state, making read node ONLINE"
@@ -488,7 +488,7 @@ if [  ${HOSTGROUP_READER_ID} -ne -1 -a ${NUMBER_READERS_ONLINE} -eq 0 ]; then
         proxysql_exec "LOAD MYSQL QUERY RULES TO RUNTIME;" 2>> ${ERR_FILE}
         echo "`date` Slave host is online, disabling read transaction from writer node" >> ${ERR_FILE}
       fi
-    fi   
+    fi
   fi
 fi
 
