Change controll of mode from disk file to scheduler parameter

diff --git a/proxysql_galera_checker b/proxysql_galera_checker
--- a/proxysql_galera_checker
+++ b/proxysql_galera_checker
@@ -6,14 +6,15 @@ usage () {
   echo "  proxysql_galera_checker --write-hg=10 --read-hg=11 --config-file=/etc/proxysql-admin.cnf --log=/var/lib/proxysql/pxc_test_proxysql_galera_check.log"
   echo ""
   echo "Options:"
-  echo "  -w, --write-hg=<NUMBER>     Specify ProxySQL write hostgroup."
-  echo "  -r, --read-hg=<NUMBER>      Specify ProxySQL read hostgroup."
-  echo "  -c, --config-file=PATH      Specify ProxySQL-admin configuration file."
-  echo "  -l, --log=PATH              Specify proxysql_galera_checker log file."
-  echo "  -n, --writer-count=<NUMBER> Maximum number of write hostgroup_id node that can be marked ONLINE"
-  echo "                              When 0 (default), all nodes can be marked ONLINE"
-  echo "  -h, --help                  Display script usage information"
-  echo "  -v, --version               Print version info"
+  echo "  -w, --write-hg=<NUMBER>             Specify ProxySQL write hostgroup."
+  echo "  -r, --read-hg=<NUMBER>              Specify ProxySQL read hostgroup."
+  echo "  -c, --config-file=PATH              Specify ProxySQL-admin configuration file."
+  echo "  -l, --log=PATH                      Specify proxysql_galera_checker log file."
+  echo "  -n, --writer-count=<NUMBER>         Maximum number of write hostgroup_id node that can be marked ONLINE"
+  echo "                                      When 0 (default), all nodes can be marked ONLINE"
+  echo "  -m, --mode=[loadbal|singlewrite]    ProxySQL read/write configuration mode, currently supporting: 'loadbal' and 'singlewrite' (the default) modes"  
+  echo "  -h, --help                          Display script usage information"
+  echo "  -v, --version                       Print version info"
   echo ""
   echo "Notes about the mysql_servers in ProxySQL:"
   echo ""
@@ -50,7 +51,7 @@ fi
 # Check if we have a functional getopt(1)
 if ! getopt --test
   then
-  go_out="$(getopt --options=w:r:c:l:n:vh --longoptions=write-hg:,read-hg:,config-file:,log:,writer-count:,version,help \
+  go_out="$(getopt --options=w:r:c:l:n:m:vh --longoptions=write-hg:,read-hg:,config-file:,log:,writer-count:,mode:,version,help \
   --name="$(basename "$0")" -- "$@")"
   test $? -eq 0 || exit 1
   eval set -- "$go_out"
@@ -97,6 +98,15 @@ do
       export NUMBER_WRITERS="$2"
       shift 2
     ;;
+    -m | --mode )
+    P_MODE="$2"
+    shift 2
+    if [ "$P_MODE" != "loadbal" ] && [ "$P_MODE" != "singlewrite" ]; then
+      echo "ERROR: Invalid --mode passed:"
+      echo "  Please choose any of these modes: loadbal, singlewrite"
+      exit 1
+    fi
+    ;;      
     -v | --version )
       echo "proxysql_galera_checker version 1.4.9"
       exit 0
@@ -215,30 +225,33 @@ else
   RELOAD_CHECK_FILE="${PROXYSQL_DATADIR}/${CLUSTER_NAME}_reload"
 fi
 
-if [[ ! -f ${PROXYSQL_DATADIR}/${CLUSTER_NAME}_mode ]] ; then
-  MODE_CHECK=$(proxysql_exec "select comment from mysql_servers where comment='WRITE' and hostgroup_id in ($WRITE_HOSTGROUP_ID, $READ_HOSTGROUP_ID)")
-  if [[ "$MODE_CHECK" == "WRITE" ]]; then
-    if [[ -z $CLUSTER_NAME ]]; then 
-      echo "singlewrite" > ${PROXYSQL_DATADIR}/mode
-	else
-      echo "singlewrite" > ${PROXYSQL_DATADIR}/${CLUSTER_NAME}_mode
-	fi
-  else
-    if [[ -z $CLUSTER_NAME ]]; then 
-      echo "loadbal" > ${PROXYSQL_DATADIR}/mode
-	else
-      echo "loadbal" > ${PROXYSQL_DATADIR}/${CLUSTER_NAME}_mode
-	fi
-  fi
-  if [[ -z $CLUSTER_NAME ]]; then 
-    MODE=$(cat ${PROXYSQL_DATADIR}/mode)
-  else
-    MODE=$(cat ${PROXYSQL_DATADIR}/${CLUSTER_NAME}_mode)  
-  fi
+if [[ ! -z $P_MODE ]] then
+  MODE=$P_MODE
 else
-  MODE=$(cat ${PROXYSQL_DATADIR}/${CLUSTER_NAME}_mode)
+  if [[ ! -f ${PROXYSQL_DATADIR}/${CLUSTER_NAME}_mode ]] ; then
+    MODE_CHECK=$(proxysql_exec "select comment from mysql_servers where comment='WRITE' and hostgroup_id in ($WRITE_HOSTGROUP_ID, $READ_HOSTGROUP_ID)")
+    if [[ "$MODE_CHECK" == "WRITE" ]]; then
+      if [[ -z $CLUSTER_NAME ]]; then 
+        echo "singlewrite" > ${PROXYSQL_DATADIR}/mode
+      else
+        echo "singlewrite" > ${PROXYSQL_DATADIR}/${CLUSTER_NAME}_mode
+	  fi
+    else
+      if [[ -z $CLUSTER_NAME ]]; then 
+        echo "loadbal" > ${PROXYSQL_DATADIR}/mode
+      else
+        echo "loadbal" > ${PROXYSQL_DATADIR}/${CLUSTER_NAME}_mode
+	  fi
+    fi
+    if [[ -z $CLUSTER_NAME ]]; then 
+      MODE=$(cat ${PROXYSQL_DATADIR}/mode)
+    else
+      MODE=$(cat ${PROXYSQL_DATADIR}/${CLUSTER_NAME}_mode)  
+    fi
+  else
+    MODE=$(cat ${PROXYSQL_DATADIR}/${CLUSTER_NAME}_mode)
+  fi
 fi
-
 # With thanks, http://bencane.com/2015/09/22/preventing-duplicate-cron-job-executions/
 if [[ -z $CLUSTER_NAME ]]; then 
   CHECKER_PIDFILE=${PROXYSQL_DATADIR}/galera_checker.pid
@@ -284,9 +297,9 @@ if [[ ! -f /usr/bin/proxysql_node_monitor ]] ;then
   exit 1
 else
   if [[ -z $CLUSTER_NAME ]]; then
-    /usr/bin/proxysql_node_monitor --config-file=$CONFIG_FILE --write-hg=$HOSTGROUP_WRITER_ID --read-hg=$HOSTGROUP_READER_ID --log=${PROXYSQL_DATADIR}/proxysql_node_monitor.log
+    /usr/bin/proxysql_node_monitor --config-file=$CONFIG_FILE --write-hg=$HOSTGROUP_WRITER_ID --read-hg=$HOSTGROUP_READER_ID --mode=$MODE --log=${PROXYSQL_DATADIR}/proxysql_node_monitor.log
   else
-    /usr/bin/proxysql_node_monitor --config-file=$CONFIG_FILE --write-hg=$HOSTGROUP_WRITER_ID --read-hg=$HOSTGROUP_READER_ID --log=${PROXYSQL_DATADIR}/${CLUSTER_NAME}_proxysql_node_monitor.log
+    /usr/bin/proxysql_node_monitor --config-file=$CONFIG_FILE --write-hg=$HOSTGROUP_WRITER_ID --read-hg=$HOSTGROUP_READER_ID --mode=$MODE --log=${PROXYSQL_DATADIR}/${CLUSTER_NAME}_proxysql_node_monitor.log
   fi
 fi
 
diff --git a/proxysql_node_monitor b/proxysql_node_monitor
--- a/proxysql_node_monitor
+++ b/proxysql_node_monitor
@@ -9,12 +9,13 @@ usage () {
   echo "  proxysql_node_monitor --write-hg=10 --read-hg=11 --config-file=/etc/proxysql-admin.cnf --log=/var/lib/proxysql/pxc_test_proxysql_galera_check.log"
   echo ""
   echo "Options:"
-  echo "  -w, --write-hg=<NUMBER>     Specify ProxySQL write hostgroup."
-  echo "  -r, --read-hg=<NUMBER>      Specify ProxySQL read hostgroup."
-  echo "  -c, --config-file=PATH      Specify ProxySQL-admin configuration file."
-  echo "  -l, --log=PATH              Specify proxysql_node_monitor log file."
-  echo "  -h, --help                  Display script usage information"
-  echo "  -v, --version               Print version info"
+  echo "  -w, --write-hg=<NUMBER>             Specify ProxySQL write hostgroup."
+  echo "  -r, --read-hg=<NUMBER>              Specify ProxySQL read hostgroup."
+  echo "  -m, --mode=[loadbal|singlewrite]    ProxySQL read/write configuration mode, currently supporting: 'loadbal' and 'singlewrite' (the default) modes"
+  echo "  -c, --config-file=PATH              Specify ProxySQL-admin configuration file."
+  echo "  -l, --log=PATH                      Specify proxysql_node_monitor log file."
+  echo "  -h, --help                          Display script usage information"
+  echo "  -v, --version                       Print version info"
 }
 
 # Check user permission to needed file.
@@ -29,7 +30,7 @@ check_permission(){
 # Check if we have a functional getopt(1)
 if ! getopt --test
   then
-  go_out="$(getopt --options=w:r:c:l:vh --longoptions=write-hg:,read-hg:,config-file:,log:,version,help \
+  go_out="$(getopt --options=w:r:c:l:vh --longoptions=write-hg:,read-hg:,mode:,config-file:,log:,version,help \
   --name="$(basename "$0")" -- "$@")"
   test $? -eq 0 || exit 1
   eval set -- "$go_out"
@@ -51,6 +52,15 @@ do
     -r | --read-hg )
       export READ_HG="$2"
       shift 2
+    ;;
+    -m | --mode )
+    P_MODE="$2"
+    shift 2
+    if [ "$P_MODE" != "loadbal" ] && [ "$P_MODE" != "singlewrite" ]; then
+      echo "ERROR: Invalid --mode passed:"
+      echo "  Please choose any of these modes: loadbal, singlewrite"
+      exit 1
+    fi
     ;;
     --config-file )
       CONFIG_FILE="$2"
@@ -142,7 +152,10 @@ if [ $debug -eq 1 ];then echoit "DEBUG MODE: $MODE" ;fi
 
 if [ $debug -eq 1 ];then echoit "DEBUG check mode name from proxysql data directory " ;fi
 CLUSTER_NAME=$(proxysql_exec "select comment from scheduler where arg1 LIKE '%--write-hg=$WRITE_HOSTGROUP_ID%'")
-if [[ -z $CLUSTER_NAME ]]; then
+
+if [[ ! -z $P_MODE ]] then
+  MODE=$P_MODE
+elif [[ -z $CLUSTER_NAME ]]; then
   if [[ -f ${PROXYSQL_DATADIR}/mode ]] ; then
     MODE=$(cat ${PROXYSQL_DATADIR}/mode)
   fi
