PSQLADM-107 : include-slaves - do not move slaves into write hostgroup even if the whole cluster went down.
Issue
The default behavior (if async slaves are used), is to add an async
slave to the WRITE hostgroup if all PXC nodes are down.

Solution
Make this into an option (--use-slave-as-writer=<yes/no>). This option
is now required to be specified if async-slaves are specified when using
proxysql-admin.

diff --git a/proxysql-admin b/proxysql-admin
--- a/proxysql-admin
+++ b/proxysql-admin
@@ -71,6 +71,7 @@ declare    CLUSTER_PORT=""
 declare    SLAVE_NODES=""
 declare    SLAVE_HOSTNAME=""
 declare    SLAVE_PORT=""
+declare    SLAVE_IS_WRITER=""
 
 declare    MODE="singlewrite"
 declare -i NODE_CHECK_INTERVAL=3000
@@ -178,9 +179,14 @@ Options:
                                      the highest priority.
   --include-slaves=host_name:port    Add specified slave node(s) to ProxySQL, these nodes will go
                                      into the reader hostgroup and will only be put into
-                                     the writer hostgroup if all cluster nodes are down.
+                                     the writer hostgroup if all cluster nodes are down (this
+                                     depends on the value of --use-slave-as-writer).
                                      Slaves must be read only.  Can accept a comma delimited list.
                                      If this is used make sure 'read_only=1' is in the slave's my.cnf
+  --use-slave-as-writer=<yes/no>     If this value is 'yes', then a slave may be used as a writer
+                                     if the entire cluster is down. If 'no', then a slave
+                                     will not be used as a writer. This option is required
+                                     if '--include-slaves' is used.
   --writer-is-reader=<value>         Defines if the writer node also accepts writes.
                                      Possible values are 'always', 'never', and 'ondemand'.
                                      'ondemand' means that the writer node only accepts reads
@@ -1127,7 +1133,7 @@ function enable_proxysql() {
   else
     number_writers=0
   fi
-  proxysql_exec "$LINENO" "INSERT INTO SCHEDULER (active,interval_ms,filename,arg1,comment) VALUES (1,$NODE_CHECK_INTERVAL,'$proxysql_galera_check','--config-file=$CONFIG_FILE --writer-is-reader=$WRITER_IS_READER --write-hg=$WRITE_HOSTGROUP_ID --read-hg=$READ_HOSTGROUP_ID --writer-count=$number_writers --mode=$MODE $host_priority --log=$PROXYSQL_DATADIR/${cluster_name}_proxysql_galera_check.log','$cluster_name');"
+  proxysql_exec "$LINENO" "INSERT INTO SCHEDULER (active,interval_ms,filename,arg1,comment) VALUES (1,$NODE_CHECK_INTERVAL,'$proxysql_galera_check','--config-file=$CONFIG_FILE --writer-is-reader=$WRITER_IS_READER --write-hg=$WRITE_HOSTGROUP_ID --read-hg=$READ_HOSTGROUP_ID --writer-count=$number_writers --mode=$MODE $host_priority --use-slave-as-writer=$SLAVE_IS_WRITER --log=$PROXYSQL_DATADIR/${cluster_name}_proxysql_galera_check.log','$cluster_name');"
   check_cmd $? $LINENO "Failed to add the PXC monitoring scheduler in ProxySQL."\
                        "\n-- Please check the ProxySQL connection parameters and status."
 
@@ -1461,7 +1467,7 @@ function parse_args() {
   # TODO: kennt, what happens if we don't have a functional getopt()?
   # Check if we have a functional getopt(1)
   if ! getopt --test; then
-    go_out="$(getopt --options=edv --longoptions=config-file:,proxysql-datadir:,proxysql-username:,proxysql-password::,proxysql-hostname:,proxysql-port:,cluster-username:,cluster-password::,cluster-hostname:,cluster-port:,monitor-username:,monitor-password:,cluster-app-username:,cluster-app-password:,node-check-interval:,quick-demo,mode:,write-node:,include-slaves:,use-existing-monitor-password,without-cluster-app-user,writer-is-reader:,enable,disable,adduser,syncusers,sync-multi-cluster-users,version,debug,help \
+    go_out="$(getopt --options=edv --longoptions=config-file:,proxysql-datadir:,proxysql-username:,proxysql-password::,proxysql-hostname:,proxysql-port:,cluster-username:,cluster-password::,cluster-hostname:,cluster-port:,monitor-username:,monitor-password:,cluster-app-username:,cluster-app-password:,node-check-interval:,quick-demo,mode:,write-node:,include-slaves:,use-slave-as-writer:,use-existing-monitor-password,without-cluster-app-user,writer-is-reader:,enable,disable,adduser,syncusers,sync-multi-cluster-users,version,debug,help \
     --name="$(basename "$0")" -- "$@")"
     check_cmd $? $LINENO "Script error: getopt() failed with arguments: $@"
     eval set -- "$go_out"
@@ -1675,6 +1681,10 @@ function parse_args() {
         SLAVE_NODES=`echo "$2" | sed 's/,/ /g'`
         shift 2
         ;;
+      --use-slave-as-writer )
+        SLAVE_IS_WRITER="$2"
+        shift 2
+        ;;
       --quick-demo )
         shift
         QUICK_DEMO=1
@@ -1821,6 +1831,21 @@ function parse_args() {
     exit 1
   fi
 
+  if [[ -n $SLAVE_NODES ]]; then
+    if [[ -z $SLAVE_IS_WRITER ]]; then
+      error "" "Missing option: If --include-slaves is used, then --use-slave-as-writer must be set also"
+      exit 1
+    fi
+  elif [[ -z $SLAVE_IS_WRITER ]]; then
+    SLAVE_IS_WRITER="no"
+  fi
+
+  if [[ ! $SLAVE_IS_WRITER =~ ^(yes|YES|no|NO)$ ]]; then
+    error "" "Invalid --use-slave-as-writer option: '$SLAVE_IS_WRITER'"
+    echo "Please choose yes or no"
+    exit 1
+  fi
+
   readonly WRITE_HOSTGROUP_ID
   readonly READ_HOSTGROUP_ID
   readonly SLAVEREAD_HOSTGROUP_ID
@@ -1829,6 +1854,9 @@ function parse_args() {
   readonly WRITE_NODES
   readonly ENABLE_PRIORITY
   readonly P_HOST_PRIORITY
+
+  readonly SLAVE_NODES
+  readonly SLAVE_IS_WRITER
 
   readonly ENABLE
   readonly DISABLE
