proxysql-admin updates

diff --git a/proxysql-admin b/proxysql-admin
--- a/proxysql-admin
+++ b/proxysql-admin
@@ -7,21 +7,25 @@
 usage () {
   echo "Usage: [ options ]"
   echo "Options:"
-    echo " --user=user_name, -u user_name         User to use when connecting to the ProxySQL service"
-    echo " --password[=password], -p[password]    Password to use when connecting to the ProxySQL service"
-    echo " --port=port_num, -P port_num           Port to use when connecting to the ProxySQL service"
-    echo " --host=host_name, -h host_name         Hostname to use when connecting to the ProxySQL service"
+    echo " --proxysql-user=user_name              User to use when connecting to the ProxySQL service"
+    echo " --proxysql-password[=password]         Password to use when connecting to the ProxySQL service"
+    echo " --proxysql-port=port_num               Port to use when connecting to the ProxySQL service"
+    echo " --proxysql-host=host_name              Hostname to use when connecting to the ProxySQL service"
+    echo " --cluster-user=user_name               User to use when connecting to the Percona XTraDB Cluster node"
+    echo " --cluster-password[=password]          Password to use when connecting to the Percona XTraDB Cluster node"
+    echo " --cluster-port=port_num                Port to use when connecting to the Percona XTraDB Cluster node"
+    echo " --cluster-host=host_name               Hostname to use when connecting to the Percona XTraDB Cluster node"
     echo " --enable                               Auto-configure Percona XtraDB Cluster nodes into ProxySQL"
     echo " --disable                              Remove Percona XtraDB Cluster configurations from ProxySQL"
     echo " --start                                Starts Percona XTraDB Cluster ProxySQL monitoring daemon"
     echo " --stop                                 Stops Percona XtraDB Cluster ProxySQL monitoring daemon"
+    echo " --status                               Checks Percona XtraDB Cluster ProxySQL monitoring daemon status."
 }
 
 # Check if we have a functional getopt(1)
 if ! getopt --test
   then
-  go_out="$(getopt --options=u:p::h:P:ed \
-  --longoptions=user:,password::,host:,port:,enable,disable,start,stop,status,help: \
+  go_out="$(getopt --options= --longoptions=proxysql-user:,proxysql-password::,proxysql-host:,proxysql-port:,cluster-user:,cluster-password::,cluster-host:,cluster-port:,enable,disable,start,stop,status,help: \
   --name="$(basename "$0")" -- "$@")"
   test $? -eq 0 || exit 1
   eval set -- $go_out
@@ -31,34 +35,64 @@ for arg
 do
   case "$arg" in
     -- ) shift; break;;
-    -u | --user )
-    usr="$2"
+    --proxysql-user )
+    proxysql_usr="$2"
     shift 2
     ;;
-    -p | --password )
+    --proxysql-password )
     case "$2" in
       "")
       read -s -p "Enter ProxySQL password:" INPUT_PASS
       if [ -z "$INPUT_PASS" ]; then
-        pass=""
+        proxysql_pass=""
 	printf "\nContinuing without ProxySQL password...\n";
       else
-        pass="-p$INPUT_PASS"
+        proxysql_pass="$INPUT_PASS"
       fi
       printf "\n"
       ;;
       *)
-      pass="-p$2"
+      proxysql_pass="$2"
       ;;
     esac
     shift 2
     ;;
-    -h | --host )
-    hostname="-h $2"
+    --proxysql-host )
+    proxysql_hostname="-h $2"
     shift 2
     ;;
-    -P | --port )
-    port="-P $2"
+    --proxysql-port )
+    proxysql_port="-P $2"
+    shift 2
+    ;;
+    --cluster-user )
+    cluster_usr="$2"
+    shift 2
+    ;;
+    --cluster-password )
+    case "$2" in
+      "")
+      read -s -p "Enter Cluster password:" INPUT_PASS
+      if [ -z "$INPUT_PASS" ]; then
+        cluster_pass=""
+	printf "\nContinuing without Cluster password...\n";
+      else
+        cluster_pass="-p$INPUT_PASS"
+      fi
+      printf "\n"
+      ;;
+      *)
+      cluster_pass="-p$2"
+      ;;
+    esac
+    shift 2
+    ;;
+    --cluster-host )
+    cluster_hostname="-h $2"
+    shift 2
+    ;;
+    --cluster-port )
+    cluster_port="-P $2"
     shift 2
     ;;
     -e | --enable )
@@ -94,36 +128,45 @@ if [[ ! -e `which mysql 2> /dev/null` ]] ;then
 fi
 
 # Check the options gathered from the command line
-if [ -z "$usr" ];then
+if [ -z "$proxysql_usr" ];then
+  echo "The ProxySQL username is required!"
+  usage
+  exit 1
+fi
+
+if [[ -z "$proxysql_hostname" ]]; then
+  proxysql_hostname="-h127.0.0.1"
+fi
+
+if [[ -z "$proxysql_port" ]]; then
+  proxysql_port="-P6032"
+fi
+
+if [ -z "$cluster_usr" ];then
   echo "The Percona XtraDB Cluster username is required!"
   usage
-  exit
-elif [[ -z "$hostname" ]]; then
-  hostname="-h127.0.0.1"
-elif [[ -z "$port" ]]; then
-  port="-P3306"
+  exit 1
+fi
+
+if [[ -z "$cluster_hostname" ]]; then
+  cluster_hostname="-hlocalhost"
+fi
+
+if [[ -z "$cluster_port" ]]; then
+  cluster_port="-P3306"
 fi
 
 PIDFILE=/tmp/pxc-proxysql-monitor.pid
 
 proxysql_connection_check(){
-  if ! mysql -u$usr $pass $hostname $port -e"show tables" >/dev/null 2>/dev/null; then 
+  if ! mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port -e"show tables" >/dev/null 2>/dev/null; then 
     echo "Please enter valid ProxySQL connection parameters! Terminating.."
     exit 1
   fi
 }
 
 pxc_connection_check(){
-  echo -e "\nPlease provide Percona XtraDB Cluster connection parameters to configure PXC nodes into ProxySQL in following format"
-  read -p "<username>:<password>:<hostname>:<port> : " read_param 
-  conn_array=(${read_param//:/ })
-  pxc_pass=`echo $read_param | cut -d":" -f2`
-  if [ -z $pxc_pass ];then
-    echo -e "\nAlert! You have given empty password!"
-    DSN="-u${conn_array[0]} -h${conn_array[1]} -P${conn_array[2]} --protocol=tcp"
-  else
-    DSN=" -u${conn_array[0]} -p${conn_array[1]} -h${conn_array[2]} -P${conn_array[3]} --protocol=tcp"
-  fi
+  DSN=" -u$cluster_usr $cluster_pass $cluster_hostname $cluster_port --protocol=tcp"
   if ! mysql $DSN -e"select @@port" >/dev/null 2>/dev/null; then 
     echo "Please enter valid PXC connection parameters! Terminating.."
     exit 1
@@ -154,6 +197,8 @@ enable_proxysql(){
   else
     PROXYSQL=`which proxysql`
     PROXYSQL_GALERA_CHECK=`which proxysql_galera_checker`
+    sed -i "0,/^[ \t]*PROXYSQL_USERNAME[ \t]*=.*$/s|^[ \t]*PROXYSQL_USERNAME[ \t]*=.*$|PROXYSQL_USERNAME=\"$proxysql_usr\"|" $PROXYSQL_GALERA_CHECK
+    sed -i "0,/^[ \t]*PROXYSQL_PASSWORD[ \t]*=.*$/s|^[ \t]*PROXYSQL_PASSWORD[ \t]*=.*$|PROXYSQL_PASSWORD=\"$proxysql_pass\"|" $PROXYSQL_GALERA_CHECK
   fi
   # Check for existing proxysql process
   if ! pidof proxysql >/dev/null ; then
@@ -177,31 +222,37 @@ enable_proxysql(){
     read -s -p "No input entered, Enter ProxySQL monitoring password: " mon_password
   done
 
-  mysql  $DSN -e "GRANT USAGE ON *.* TO $mon_uname@'%' IDENTIFIED BY '$mon_password';" 2>/dev/null
-  check_cmd $?  "Cannot create the ProxySQL monitoring user"
-  echo "update global_variables set variable_value='$mon_uname' where variable_name='mysql-monitor_username'; update global_variables set variable_value='$mon_password' where variable_name='mysql-monitor_password'; " | mysql -u$usr $pass $hostname $port 2>/dev/null
-  check_cmd $?  "Cannot set the mysql-monitor variables in ProxySQL"
-  echo "LOAD MYSQL VARIABLES TO RUNTIME;SAVE MYSQL VARIABLES TO DISK;" | mysql -u$usr $pass $hostname $port 2>/dev/null
+  check_user=`mysql  $DSN -Bse"SELECT user,host FROM mysql.user where user='$mon_uname' and host='%';" 2>/dev/null`
+  if [[ -z "$check_user" ]]; then
+    mysql  $DSN -e "GRANT USAGE ON *.* TO $mon_uname@'%' IDENTIFIED BY '$mon_password';" 2>/dev/null
+    check_cmd $?  "Cannot create the ProxySQL monitoring user"
+    echo "update global_variables set variable_value='$mon_uname' where variable_name='mysql-monitor_username'; update global_variables set variable_value='$mon_password' where variable_name='mysql-monitor_password'; " | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
+    check_cmd $?  "Cannot set the mysql-monitor variables in ProxySQL"
+    echo "LOAD MYSQL VARIABLES TO RUNTIME;SAVE MYSQL VARIABLES TO DISK;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
+    echo -e "\n\nUser $mon_uname@'%' has been added with USAGE privilege\n"
+  else
+    echo -e "\n\nUser ${mon_uname}@'%' already present in Percona XtraDB Cluster"
+  fi
 
   # Adding Percona XtraDB Cluster nodes to ProxySQL
-  echo -e "\n\nAdding the Percona XtraDB Cluster server nodes to ProxySQL"
-  echo "DELETE FROM mysql_servers WHERE hostgroup_id=10" | mysql -u$usr $pass $hostname $port 2>/dev/null
+  echo -e "\nAdding the Percona XtraDB Cluster server nodes to ProxySQL"
+  echo "DELETE FROM mysql_servers WHERE hostgroup_id=10" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
   wsrep_address=(`mysql  $DSN -Bse "show status like 'wsrep_incoming_addresses'" 2>/dev/null | awk '{print $2}' | sed 's|,| |g'`)
   for i in "${wsrep_address[@]}"; do	
     ws_ip=`echo $i | cut -d':' -f1`
     ws_port=`echo $i | cut -d':' -f2`
-    echo "INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight) VALUES ('$ws_ip',10,$ws_port,1000);" | mysql -u$usr $pass $hostname $port 2>/dev/null
+    echo "INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight) VALUES ('$ws_ip',10,$ws_port,1000);" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
     check_cmd $? "Failed to add the Percona XtraDB Cluster server node $ws_ip:$ws_port"
   done
-  echo "LOAD MYSQL SERVERS TO RUNTIME; SAVE MYSQL SERVERS TO DISK;" | mysql -u$usr $pass $hostname $port 2>/dev/null
+  echo "LOAD MYSQL SERVERS TO RUNTIME; SAVE MYSQL SERVERS TO DISK;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
 
   # Adding Percona XtraDB Cluster monitoring script
 
-  echo "DELETE FROM SCHEDULER WHERE ID=10;" | mysql -u$usr $pass $hostname $port 2>/dev/null
+  echo "DELETE FROM SCHEDULER WHERE ID=10;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
   check_cmd $?
-  echo "INSERT  INTO SCHEDULER (id,active,interval_ms,filename,arg1,arg2,arg3,arg4,arg5) VALUES (10,1,2000,'$PROXYSQL_GALERA_CHECK',10,10,${#wsrep_address[@]},1,'/var/lib/proxysql/galera-check.log');" | mysql -u$usr $pass $hostname $port 2>/dev/null
+  echo "INSERT  INTO SCHEDULER (id,active,interval_ms,filename,arg1,arg2,arg3,arg4,arg5) VALUES (10,1,2000,'$PROXYSQL_GALERA_CHECK',10,10,${#wsrep_address[@]},1,'/var/lib/proxysql/galera-check.log');" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
   check_cmd $? "Failed to add the Percona XtraDB Cluster monitoring scheduler in ProxySQL"
-  echo "LOAD SCHEDULER TO RUNTIME;SAVE SCHEDULER TO DISK;" | mysql -u$usr $pass $hostname $port 2>/dev/null
+  echo "LOAD SCHEDULER TO RUNTIME;SAVE SCHEDULER TO DISK;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
 
   echo -e "\nConfiguring Percona XtraDB Cluster user to connect through ProxySQL"
   echo -n "Enter Percona XtraDB Cluster user name: "
@@ -216,15 +267,16 @@ enable_proxysql(){
   do
     read -s -p "No input entered, Enter Percona XtraDB Cluster user password: " pxc_password
   done
-  check_user=`mysql  $DSN -Bse"SELECT user,host FROM mysql.user where user='$pxc_uname' and host='%';"`
+  check_user=`mysql  $DSN -Bse"SELECT user,host FROM mysql.user where user='$pxc_uname' and host='%';" 2>/dev/null`
 
   if [[ -z "$check_user" ]]; then
-    mysql  $DSN -e "GRANT CREATE, DROP, LOCK TABLES, REFERENCES, EVENT, ALTER, DELETE, INDEX, INSERT, SELECT, UPDATE, CREATE TEMPORARY TABLES, TRIGGER, CREATE VIEW, SHOW VIEW, ALTER ROUTINE, CREATE ROUTINE  ON test.* TO $pxc_uname@'%' IDENTIFIED BY '$pxc_password';" 2>/dev/null
+    mysql  $DSN -e "GRANT USAGE  ON *.* TO $pxc_uname@'%' IDENTIFIED BY '$pxc_password';" 2>/dev/null
     check_cmd $? "Cannot add Percona XtraDB Cluster user : $pxc_uname (GRANT)"
-    echo "INSERT INTO mysql_users (username,password,active,default_hostgroup) values ('$pxc_uname','$pxc_password',1,10);LOAD MYSQL USERS TO RUNTIME;SAVE MYSQL USERS FROM RUNTIME;SAVE MYSQL USERS TO DISK;" | mysql -u$usr $pass $hostname $port 2>/dev/null
+    echo "INSERT INTO mysql_users (username,password,active,default_hostgroup) values ('$pxc_uname','$pxc_password',1,10);LOAD MYSQL USERS TO RUNTIME;SAVE MYSQL USERS FROM RUNTIME;SAVE MYSQL USERS TO DISK;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
     check_cmd $? "Cannot add Percona XtraDB Cluster user : $pxc_uname (mysql_users update)"
+    echo -e "\n\nUser $pxc_uname@'%' has been added with USAGE privilege, please make sure to grant appropriate privileges\n"
   else
-    echo -e "\nUser ${pxc_uname}@'%' already present in Percona XtraDB Cluster"
+    echo -e "\n\nUser ${pxc_uname}@'%' already present in Percona XtraDB Cluster"
   fi
 
   if [ -f $PIDFILE ]; then
@@ -240,9 +292,9 @@ enable_proxysql(){
 # Removing PXC configuration from proxysql
 disable_proxysql(){
   proxysql_connection_check
-  echo "DELETE FROM mysql_users WHERE default_hostgroup=10;" | mysql -u$usr $pass $hostname $port 2>/dev/null
+  echo "DELETE FROM mysql_users WHERE default_hostgroup=10;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
   check_cmd $? "Cannot delete Percona XtraDB Cluster users from ProxySQL"
-  echo "DELETE FROM mysql_servers WHERE hostgroup_id=10;" | mysql -u$usr $pass $hostname $port 2>/dev/null
+  echo "DELETE FROM mysql_servers WHERE hostgroup_id=10;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
   check_cmd $? "Cannot delete Percona XtraDB Cluster nodes from ProxySQL"
   if [ -f $PIDFILE ]; then
     PID=$(cat ${PIDFILE});
@@ -258,18 +310,18 @@ start_daemon(){
   while true
   do
     check_proxysql
-    current_hosts=(`mysql -u$usr $pass $hostname $port -Bse"SELECT hostname,port FROM mysql_servers WHERE status='ONLINE'" | sed 's|\t|:|g' | tr '\n' ' '`)
+    current_hosts=(`mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port -Bse"SELECT hostname,port FROM mysql_servers WHERE status='ONLINE'" | sed 's|\t|:|g' | tr '\n' ' '`)
     wsrep_address=(`mysql  $DSN -Bse "SHOW STATUS LIKE 'wsrep_incoming_addresses'" 2>/dev/null | awk '{print $2}' | sed 's|,| |g'`)
     for i in "${wsrep_address[@]}"; do
       if [[ ! " ${current_hosts[@]} " =~ " ${i} " ]]; then
-        echo "DELETE FROM mysql_servers WHERE hostgroup_id=10;" | mysql -u$usr $pass $hostname $port 2>/dev/null
+        echo "DELETE FROM mysql_servers WHERE hostgroup_id=10;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
         for i in "${wsrep_address[@]}"; do	
           ws_ip=`echo $i | cut -d':' -f1`
           ws_port=`echo $i | cut -d':' -f2`
-          echo "INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight) VALUES ('$ws_ip',10,$ws_port,1000);" | mysql -u$usr $pass $hostname $port 2>/dev/null
+          echo "INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight) VALUES ('$ws_ip',10,$ws_port,1000);" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
           check_cmd $? "Cannot add Percona XtraDB Cluster server node $ws_ip:$ws_port"
         done
-        echo "LOAD MYSQL SERVERS TO RUNTIME; SAVE MYSQL SERVERS TO DISK;" | mysql -u$usr $pass $hostname $port 2>/dev/null
+        echo "LOAD MYSQL SERVERS TO RUNTIME; SAVE MYSQL SERVERS TO DISK;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
         break
       fi
     done
@@ -326,7 +378,7 @@ if [ "$enable" == 1 -o "$disable" == 1 -o "$start_daemon"  == 1 -o "$stop_daemon
       echo "Percona XtraDB Cluster ProxySQL monitoring daemon not started"
     else
       check_proxysql
-      PXC_NODES_CHECK=`mysql -u$usr $pass $hostname $port -Bse"SELECT COUNT(*) FROM mysql_servers WHERE hostgroup_id=10;"`
+      PXC_NODES_CHECK=`mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port -Bse"SELECT COUNT(*) FROM mysql_servers WHERE hostgroup_id=10;" 2>/dev/null`
       if [ $PXC_NODES_CHECK -eq 0 ]; then
         echo "Percona XtraDB Cluster is not configured in ProxySQL. Please add PXC nodes into ProxySQL before starting monitorning daemon."
         exit 1
@@ -348,6 +400,7 @@ if [ "$enable" == 1 -o "$disable" == 1 -o "$start_daemon"  == 1 -o "$stop_daemon
     status_daemon
   fi
 else
+  echo "Usage: proxysql-admin <user credentials> {enable|disable|start|stop|status}"
   usage
 fi
 
