singlewrite mode updates for handling WRITE node offline status

diff --git a/proxysql-admin b/proxysql-admin
--- a/proxysql-admin
+++ b/proxysql-admin
@@ -7,7 +7,7 @@
 # Make sure only root can run this script
 if [ $(id -u) -ne 0 ]; then
   echo "ERROR: This script must be run as root!" 1>&2
-  exit
+  exit 1
 fi
 
 # Dispay script usage details
@@ -39,7 +39,7 @@ usage () {
 # Check if we have a functional getopt(1)
 if ! getopt --test
   then
-  go_out="$(getopt --options= --longoptions=proxysql-user:,proxysql-password::,proxysql-host:,proxysql-port:,cluster-user:,cluster-password::,cluster-host:,cluster-port:,monitor-user:,monitor-password:,pxc-app-user:,pxc-app-password:,galera-check-interval:,mode:,config-file:,enable,disable,adduser,help \
+  go_out="$(getopt --options= --longoptions=proxysql-user:,proxysql-password::,proxysql-host:,proxysql-port:,cluster-user:,cluster-password::,cluster-host:,cluster-port:,monitor-user:,monitor-password:,pxc-app-user:,pxc-app-password:,galera-check-interval:,mode:,write-node:,config-file:,enable,disable,adduser,help \
   --name="$(basename "$0")" -- "$@")"
   test $? -eq 0 || exit 1
   eval set -- $go_out
@@ -231,6 +231,12 @@ fi
 
 if [[ -z "$RW_MODE" ]]; then
   RW_MODE="loadbal"
+else
+  if [ $RW_MODE != "loadbal" -a $RW_MODE != "singlewrite" ]; then
+    echo "ERROR: Invalid --mode passed:"
+    echo "  Please choose any of these modes loadbal|singlewrite"
+    exit 1
+  fi
 fi
 
 PIDFILE=/tmp/pxc-proxysql-monitor.pid
@@ -409,11 +415,25 @@ enable_proxysql(){
       read -r -p  "You have not given writer node info through command line/config-file. Please enter writer-node info (eg : 127.0.0.1:3306): " WRITE_NODE
       writer_ws_ip=$(echo $WRITE_NODE | cut -d':' -f1)
       writer_ws_port=$(echo $WRITE_NODE | cut -d':' -f2)
+      printf "[client]\nuser=${CLUSTER_USERNAME}\npassword=${CLUSTER_PASSWORD}\nhost=${writer_ws_ip}\nport=${writer_ws_port}\n" | mysql --defaults-file=/dev/stdin --protocol=tcp -Bse "select @@port" >/dev/null 2>/dev/null
+      if [ $? -ne 0 ]; then 
+        echo -e "\nERROR: Could not establish connection to write node $writer_ws_ip:$writer_ws_port. Terminating!\n"; 
+        proxysql_exec "DELETE FROM mysql_users WHERE default_hostgroup in ($WRITE_HOSTGROUP_ID,$READ_HOSTGROUP_ID);"
+        check_cmd $? "Cannot delete Percona XtraDB Cluster users from ProxySQL"
+        exit 1
+      fi
     else
       writer_ws_ip=$(echo $WRITE_NODE | cut -d':' -f1)
       writer_ws_port=$(echo $WRITE_NODE | cut -d':' -f2)
+      printf "[client]\nuser=${CLUSTER_USERNAME}\npassword=${CLUSTER_PASSWORD}\nhost=${writer_ws_ip}\nport=${writer_ws_port}\n" | mysql --defaults-file=/dev/stdin --protocol=tcp -Bse "select @@port" >/dev/null 2>/dev/null
+      if [ $? -ne 0 ]; then 
+        echo -e "\nERROR: Could not establish connection to write node $writer_ws_ip:$writer_ws_port. Terminating!\n"; 
+        proxysql_exec "DELETE FROM mysql_users WHERE default_hostgroup in ($WRITE_HOSTGROUP_ID,$READ_HOSTGROUP_ID);"
+        check_cmd $? "Cannot delete Percona XtraDB Cluster users from ProxySQL"
+        exit 1
+      fi
     fi
-    echo -e "\nAdding the Percona XtraDB Cluster server nodes to ProxySQL"
+
     proxysql_exec "DELETE FROM mysql_servers WHERE hostgroup_id=$WRITE_HOSTGROUP_ID"
     wsrep_address=(`mysql_exec "show status like 'wsrep_incoming_addresses'" | awk '{print $2}' | sed 's|,| |g'`)
     for i in "${wsrep_address[@]}"; do	
diff --git a/proxysql_node_monitor b/proxysql_node_monitor
--- a/proxysql_node_monitor
+++ b/proxysql_node_monitor
@@ -19,8 +19,7 @@ check_cmd(){
   MPID=$1
   ERROR_MSG=$2
   if [ ${MPID} -ne 0 ]; then 
-    echo "Assert! $ERROR_MSG. Terminating!" >> $ERR_FILE
-    exit 1
+    echo "WARNING: $ERROR_MSG." >> $ERR_FILE
   fi
 }
 
@@ -80,7 +79,7 @@ update_cluster(){
       ws_status=$(echo `proxysql_exec "SELECT status from mysql_servers WHERE hostname='$ws_ip' and port=$ws_port"`)
       echo "Cluster node (${i}) current status '$ws_status' in ProxySQL database!" >> $ERR_FILE 
       if [ "$ws_status" == "OFFLINE_HARD" ]; then
-	      proxysql_exec "UPDATE mysql_servers set status = 'OFFLINE_SOFT' WHERE hostname='$ws_ip' and port=$ws_port;"
+	proxysql_exec "UPDATE mysql_servers set status = 'OFFLINE_SOFT' WHERE hostname='$ws_ip' and port=$ws_port;"
         check_cmd $? "Cannot update Percona XtraDB Cluster node $ws_ip:$ws_port to ProxySQL database, Please check proxysql credentials" 
         proxysql_exec "LOAD MYSQL SERVERS TO RUNTIME; SAVE MYSQL SERVERS TO DISK;"
         echo "${i} node set to OFFLINE_SOFT status to ProxySQL database." >> $ERR_FILE
@@ -90,6 +89,20 @@ update_cluster(){
     fi
   done
   proxysql_exec "UPDATE SCHEDULER SET arg3=${#wsrep_address[@]} WHERE id=$SCHEDULER_ID;LOAD SCHEDULER TO RUNTIME;SAVE SCHEDULER TO DISK;"
+}
+
+mode_change_check(){
+  checkwriter_hid=`proxysql_exec "select hostgroup_id from mysql_servers where comment='WRITE' and status='OFFLINE_SOFT'"`
+  if [[ -n "$checkwriter_hid" ]]; then
+    proxysql_exec "UPDATE mysql_servers set hostgroup_id = $READ_HOSTGROUP_ID, comment='READ' WHERE comment='WRITE' and status='OFFLINE_SOFT'"
+    check_cmd $? "Cannot update Percona XtraDB Cluster writer node in ProxySQL database, Please check proxysql credentials"
+    current_hosts=(`proxysql_exec "SELECT hostname,port FROM mysql_servers WHERE  status='ONLINE' and comment='READ'  ORDER BY random() LIMIT 1" | sed 's|\t|:|g' | tr '\n' ' '`)
+    ws_ip=$(echo $current_hosts | cut -d':' -f1)
+    ws_port=$(echo $current_hosts | cut -d':' -f2)
+    proxysql_exec "UPDATE mysql_servers set hostgroup_id = $WRITE_HOSTGROUP_ID, comment='WRITE' WHERE hostname='$ws_ip' and port=$ws_port"
+    check_cmd $? "Cannot update Percona XtraDB Cluster writer node in ProxySQL database, Please check proxysql credentials"
+    proxysql_exec "LOAD MYSQL SERVERS TO RUNTIME; SAVE MYSQL SERVERS TO DISK;"
+  fi
 }
 
 CLUSTER_USERNAME=$(proxysql_exec "SELECT variable_value FROM global_variables WHERE variable_name='mysql-monitor_username'")
@@ -108,6 +121,7 @@ if [[ -z $CLUSTER_HOST_INFO ]]; then
   echo "Percona XtraDB Cluster nodes are not configured in ProxySQL database. Please pass correct info" >> $ERR_FILE
 else
   update_cluster
+  mode_change_check
 fi
 
 if [ $CHECK_STATUS -eq 1 ]; then
