Added the --include-slaves option to proxysql-admin.  This option allows slave node to be automatically added to ProxySQL and will be monitored for status.  The slavve nodes will be used as an emergency fallback if all the XtraDB cluster nodes are in a state other than ONLINE. - A slave node will be considered online as long as slave health is good (slave sql running) and it's behind no more than 3600 seconds according to the 'Seconds_Behind_Master' stat. - A slave that has fallen behind more than 3600 seconds will be put into an 'OFFLINE_SOFT' state until it catches up. - When the last available XtraDB Cluster node goes into a non-online state, the first available and 'ONLINE' slave node will be made active in the write hostgroup.   If no ONLINE slaves are found, any other slave will be randomly picked and put online provided it's slave_sql_running is 'Yes'. - Slave SQL Running = 'No' will trigger an 'OFFLINE_HARD' state. - Slave IO running != 'Yes' will trigger an 'OFFLINE_SOFT' state. - As soon as one cluster node comes back into an 'ONLINE' state, any slave in the writer hostgroup will be moved to the reader hostgroup. - If all the nodes including the slave are down everything will be down (obviously), if the slave is started back up as an emergency measure it will be made ONLINE and put in the writer hostgroup. Notes:   Slave nodes need the 'read_only' variable set to 1 (ON)   The monitoring user needs the 'REPLICATION CLIENT' privilege on the slaves

diff --git a/proxysql-admin b/proxysql-admin
--- a/proxysql-admin
+++ b/proxysql-admin
@@ -59,7 +59,10 @@ usage () {
   echo "  --mode=[loadbal|singlewrite]       ProxySQL read/write configuration mode, currently supporting: 'loadbal' and 'singlewrite' (the default) modes"
   echo "  --write-node=host_name:port        Writer node to accept write statments. This option is supported only when using --mode=singlewrite"
   echo "                                     Can accept comma delimited list with the first listed being the highest priority"
+  echo "                                     If this is used make sure 'read_only=1' is in the slave's my.cnf"
 ### Consider adding a select or prompt option for --write-node that will let you select from discovered nodes during setup ###
+  echo "  --include-slaves=host_name:port    Add specified slave node(s) to ProxySQL, these nodes will go into the reader hostgroup and will only be put into"
+  echo "                                     the writer hostgroup if all cluster nodes are down.  Slaves must read only.  Can accept comma delimited list."
   echo "  --adduser                          Adds the Percona XtraDB Cluster application user to the ProxySQL database"
   echo "  --syncusers                        Sync user accounts currently configured in MySQL to ProxySQL (deletes ProxySQL users not in MySQL)"
   echo "  --version, -v                      Print version info"
@@ -68,7 +71,7 @@ usage () {
 # Check if we have a functional getopt(1)
 if ! getopt --test
   then
-  go_out="$(getopt --options=edv --longoptions=config-file:,proxysql-username:,proxysql-password::,proxysql-hostname:,proxysql-port:,cluster-username:,cluster-password::,cluster-hostname:,cluster-port:,monitor-username:,monitor-password:,cluster-app-username:,cluster-app-password:,node-check-interval:,quick-demo,mode:,write-node:,enable,disable,adduser,syncusers,version,help \
+  go_out="$(getopt --options=edv --longoptions=config-file:,proxysql-username:,proxysql-password::,proxysql-hostname:,proxysql-port:,cluster-username:,cluster-password::,cluster-hostname:,cluster-port:,monitor-username:,monitor-password:,cluster-app-username:,cluster-app-password:,node-check-interval:,quick-demo,mode:,write-node:,include-slaves:,enable,disable,adduser,syncusers,version,help \
   --name="$(basename "$0")" -- "$@")"
   test $? -eq 0 || exit 1
   eval set -- "$go_out"
@@ -226,6 +229,11 @@ do
     fi
     shift 2
     ;;
+    --include-slaves )
+      SLAVE_NODES=`echo "$2" | sed 's/,/ /g'`
+#     enable_slaves=1
+    shift 2
+    ;;
     --quick-demo )
     shift
     QUICK_DEMO="YES"
@@ -367,14 +375,16 @@ else
 fi
 
 if [ $MODE == "loadbal" ]; then
-  WRITE_HOSTGROUP_ID=10
-  READ_HOSTGROUP_ID=10
+  SLAVEREAD_HOSTGROUP_ID=$READ_HOSTGROUP_ID
+#  WRITE_HOSTGROUP_ID=10
+  READ_HOSTGROUP_ID=$WRITE_HOSTGROUP_ID
   if [ -e "${CONFIG_FILE}" ]; then
     sudo sed -i "0,/^[ \t]*export MODE[ \t]*=.*$/s|^[ \t]*export MODE[ \t]*=.*$|export MODE=\"loadbal\"|" "${CONFIG_FILE}"
   fi
 elif [ $MODE == "singlewrite" ]; then
-  WRITE_HOSTGROUP_ID=10
-  READ_HOSTGROUP_ID=11
+#  WRITE_HOSTGROUP_ID=10
+#  READ_HOSTGROUP_ID=11
+  SLAVEREAD_HOSTGROUP_ID=$READ_HOSTGROUP_ID
   if [ -e "${CONFIG_FILE}" ]; then
     sudo sed -i "0,/^[ \t]*export MODE[ \t]*=.*$/s|^[ \t]*export MODE[ \t]*=.*$|export MODE=\"singlewrite\"|" "${CONFIG_FILE}"
   fi
@@ -392,6 +402,12 @@ proxysql_exec() {
 mysql_exec() {
   query=$1
   printf "[client]\nuser=${CLUSTER_USERNAME}\npassword=${CLUSTER_PASSWORD}\nhost=${CLUSTER_HOSTNAME}\nport=${CLUSTER_PORT}\n" | \
+      mysql --defaults-file=/dev/stdin --protocol=tcp -Bse "${query}" 2>/dev/null
+}
+
+slave_exec() {
+  query=$1
+  printf "[client]\nuser=${CLUSTER_USERNAME}\npassword=${CLUSTER_PASSWORD}\nhost=${SLAVE_HOSTNAME}\nport=${SLAVE_PORT}\n" | \
       mysql --defaults-file=/dev/stdin --protocol=tcp -Bse "${query}" 2>/dev/null
 }
 
@@ -564,13 +580,47 @@ enable_proxysql(){
   echo -e "\nConfiguring the Percona XtraDB Cluster application user to connect through ProxySQL"
   user_input_check CLUSTER_APP "Percona XtraDB Cluster application user" $WRITE_HOSTGROUP_ID
 
+  # Get the nodes in the cluster
+  wsrep_address=($(mysql_exec "show status like 'wsrep_incoming_addresses'" | awk '{print $2}' | sed 's|,| |g'))
+
+  # If any slave nodes were specified, verify they are replicating from a valid cluster node
+  if [ -n "$SLAVE_NODES" ];then
+    echo -e "\nVerifying specified slave nodes"
+    for i in $SLAVE_NODES;do
+      SLAVE_HOSTNAME=`echo $i | cut -d: -f1`
+      SLAVE_PORT=`echo $i | cut -d: -f2`
+      # Verify we can connect to the slave
+      slave_exec 'show slave status\G' > /dev/null
+      check_cmd $? "Failed to connect to $i, please check username, password and other options for connecting to the slave"
+      # Check each of the specified slaves and verify they are a slave of one of the XtraDB cluster nodes
+      slave_master=$(slave_exec 'show slave status\G'| egrep "Master_Host|Master_Port" | sed 's/ //g' | cut -d: -f2 | tr '\n' ':' | sed 's/:$//g')
+      if [[ ${wsrep_address[*]} != *"$slave_master"* ]]; then
+        echo -e "\nERROR: The slave node's master ($slave_master) does not exist in WSREP incoming address(${wsrep_address[*]})."
+        echo -e "The specified slave is not replicating from any of the XDtraDB cluster nodes, this is not supported"
+        echo -e "Please configure ProxySQL manually.. Terminating!"
+        exit 1
+      fi
+      # Verify the slave read-only variable is set to '1'
+      slave_ro=$(slave_exec 'SELECT @@read_only')
+      if [ "$slave_ro" != "1" ];then
+        echo -e "\nERROR: The slave $i is not set to read only.  Add 'read_only=1' to the my.cnf on the slave"
+        echo -e "and restart MySQL.  Execute 'SET GLOBAL read_only = 1' on the slave to avoid the restart"
+        echo -e "Correct this on slave nodes and run proxysql-admin again. Terminating!"
+        exit 1
+      fi
+    done
+    # GRANT REPLICATION CLIENT permissions to the monitoring user account
+    echo -e "\nGranting 'REPLICATION CLIENT' privilege to $MONITOR_USERNAME@$USER_HOST_RANGE"
+    mysql_exec "GRANT REPLICATION CLIENT ON *.* TO $MONITOR_USERNAME@'$USER_HOST_RANGE';"
+    check_cmd $? "$CLUSTER_USERNAME@'$CLUSTER_HOSTNAME' does not have the GRANT privilege required to assign the requested permissions"
+  fi
+
   # Adding Percona XtraDB Cluster nodes to ProxySQL
   echo -e "\nAdding the Percona XtraDB Cluster server nodes to ProxySQL"
   # Delete an existing host priority file if its there
   rm -f $HOST_PRIORITY_FILE
   if [ $MODE == "loadbal" ]; then
     proxysql_exec "DELETE FROM mysql_servers WHERE hostgroup_id=$WRITE_HOSTGROUP_ID"
-    wsrep_address=($(mysql_exec "show status like 'wsrep_incoming_addresses'" | awk '{print $2}' | sed 's|,| |g'))
     for i in "${wsrep_address[@]}"; do	
       ws_ip=$(echo "$i" | cut -d':' -f1)
       ws_port=$(echo "$i" | cut -d':' -f2)
@@ -605,7 +655,6 @@ enable_proxysql(){
       writer_ws_port=$CLUSTER_PORT
     fi
     proxysql_exec "DELETE FROM mysql_servers WHERE hostgroup_id=$WRITE_HOSTGROUP_ID"
-    wsrep_address=($(mysql_exec "show status like 'wsrep_incoming_addresses'" | awk '{print $2}' | sed 's|,| |g'))
     if [[ ${wsrep_address[*]} != *"$writer_ws_ip:$writer_ws_port"* ]]; then
       echo -e "\nERROR: Writer node cluster address($writer_ws_ip:$writer_ws_port) does not exist in WSREP incoming address(${wsrep_address[*]})."
       echo -e "Different wsrep incoming and cluster IP addresses are not supported by proxysql-admin at this time"
@@ -626,7 +675,7 @@ enable_proxysql(){
         echo " $i"
       done
     fi
-	
+
     for i in "${wsrep_address[@]}"; do	
       ws_ip=$(echo "$i" | cut -d':' -f1)
       ws_port=$(echo "$i" | cut -d':' -f2)
@@ -643,6 +692,18 @@ enable_proxysql(){
     proxysql_exec "INSERT INTO mysql_query_rules (username,destination_hostgroup,active,match_digest,apply) values('$CLUSTER_APP_USERNAME',$WRITE_HOSTGROUP_ID,1,'^SELECT.*FOR UPDATE',1),('$CLUSTER_APP_USERNAME',$READ_HOSTGROUP_ID,1,'^SELECT ',1);"
     check_cmd $? "Failed to add the read query rule. Please check username, password and other options for connecting to ProxySQL database"
     proxysql_exec "LOAD MYSQL SERVERS TO RUNTIME; SAVE MYSQL SERVERS TO DISK;LOAD MYSQL QUERY RULES TO RUNTIME;SAVE MYSQL QUERY RULES TO DISK;"
+  fi
+
+  # Adding slave nodes here if specified
+  if [ -n "$SLAVE_NODES" ];then
+    echo -e "\nAdding the following slave server nodes to ProxySQL:"
+    for i in $SLAVE_NODES;do
+      ws_ip=$(echo "$i" | cut -d':' -f1)
+      ws_port=$(echo "$i" | cut -d':' -f2)
+      proxysql_exec "INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight,comment) VALUES ('$ws_ip',$SLAVEREAD_HOSTGROUP_ID,$ws_port,1000,'SLAVEREAD');"
+      check_cmd $? "Failed to add the slave node $ws_ip:$ws_port. Please check username, password and other options for connecting to ProxySQL database"
+      echo " $i"
+    done
   fi
 
   # Adding Percona XtraDB Cluster monitoring scripts
