ProxySQL admin script updates

diff --git a/proxysql-admin b/proxysql-admin
--- a/proxysql-admin
+++ b/proxysql-admin
@@ -17,15 +17,13 @@ usage () {
     echo " --cluster-host=host_name               Hostname to use when connecting to the Percona XTraDB Cluster node"
     echo " --enable                               Auto-configure Percona XtraDB Cluster nodes into ProxySQL"
     echo " --disable                              Remove Percona XtraDB Cluster configurations from ProxySQL"
-    echo " --start                                Starts Percona XTraDB Cluster ProxySQL monitoring daemon"
-    echo " --stop                                 Stops Percona XtraDB Cluster ProxySQL monitoring daemon"
-    echo " --status                               Checks Percona XtraDB Cluster ProxySQL monitoring daemon status."
+    echo " --galera-check-interval                Interval for monitoring proxysql_galera_checker script(in milliseconds)"
 }
 
 # Check if we have a functional getopt(1)
 if ! getopt --test
   then
-  go_out="$(getopt --options= --longoptions=proxysql-user:,proxysql-password::,proxysql-host:,proxysql-port:,cluster-user:,cluster-password::,cluster-host:,cluster-port:,enable,disable,start,stop,status,help: \
+  go_out="$(getopt --options= --longoptions=proxysql-user:,proxysql-password::,proxysql-host:,proxysql-port:,cluster-user:,cluster-password::,cluster-host:,cluster-port:,galera-check-interval:,enable,disable,start,stop,status,help: \
   --name="$(basename "$0")" -- "$@")"
   test $? -eq 0 || exit 1
   eval set -- $go_out
@@ -58,11 +56,11 @@ do
     shift 2
     ;;
     --proxysql-host )
-    proxysql_hostname="-h $2"
+    proxysql_hostname="$2"
     shift 2
     ;;
     --proxysql-port )
-    proxysql_port="-P $2"
+    proxysql_port="$2"
     shift 2
     ;;
     --cluster-user )
@@ -103,17 +101,9 @@ do
     shift
     disable=1
     ;;
-    --start )
-    shift
-    start_daemon=1
-    ;;
-    --stop )
-    shift
-    stop_daemon=1
-    ;;
-    --status )
-    shift
-    status_daemon=1
+    --galera-check-interval )
+    galera_check_interval="$2"
+    shift 2
     ;;
     --help )
     usage
@@ -156,10 +146,13 @@ if [[ -z "$cluster_port" ]]; then
   cluster_port="-P3306"
 fi
 
+if [[ -z "$galera_check_interval" ]]; then
+  galera_check_interval=3000
+fi
 PIDFILE=/tmp/pxc-proxysql-monitor.pid
 
 proxysql_connection_check(){
-  if ! mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port -e"show tables" >/dev/null 2>/dev/null; then 
+  if ! mysql -u$proxysql_usr -p$proxysql_pass -h$proxysql_hostname -P$proxysql_port -e"show tables" >/dev/null 2>/dev/null; then 
     echo "Please enter valid ProxySQL connection parameters! Terminating.."
     exit 1
   fi
@@ -188,15 +181,19 @@ check_proxysql(){
 # Auto configure Percona XtraDB Cluster nodes into ProxySQL
 enable_proxysql(){
   # Checking proxysql binary location
-  if [[ ! -e `which proxysql 2> /dev/null` ]]; then
+  if [[ ! -e $(which proxysql 2> /dev/null) ]]; then
     echo "The proxysql binary was not found, please install the ProxySQL package"  
     exit 1
-  elif [[ ! -e `which proxysql_galera_checker 2> /dev/null` ]] ;then
+  elif [[ ! -e $(which proxysql_galera_checker 2> /dev/null) ]] ;then
     echo "The proxysql_galera_checker binary was not found, please check ProxySQL package installation"  
     exit 1
+  elif [[ ! -e $(which proxysql_node_monitor 2> /dev/null) ]]; then
+    echo "The proxysql_node_monitor binary was not found, please check ProxySQL package installation"  
+    exit 1
   else
-    PROXYSQL=`which proxysql`
-    PROXYSQL_GALERA_CHECK=`which proxysql_galera_checker`
+    PROXYSQL=$(which proxysql)
+    PROXYSQL_GALERA_CHECK=$(which proxysql_galera_checker)
+    PROXYSQL_NODE_MONITOR=$(which proxysql_node_monitor)
     sed -i "0,/^[ \t]*PROXYSQL_USERNAME[ \t]*=.*$/s|^[ \t]*PROXYSQL_USERNAME[ \t]*=.*$|PROXYSQL_USERNAME=\"$proxysql_usr\"|" $PROXYSQL_GALERA_CHECK
     sed -i "0,/^[ \t]*PROXYSQL_PASSWORD[ \t]*=.*$/s|^[ \t]*PROXYSQL_PASSWORD[ \t]*=.*$|PROXYSQL_PASSWORD=\"$proxysql_pass\"|" $PROXYSQL_GALERA_CHECK
   fi
@@ -206,6 +203,15 @@ enable_proxysql(){
     exit 1
   fi
   proxysql_connection_check
+
+  #creating proxysql-admin.cnf file with proxysql user credentials for checking cluster node membership.
+  echo "export proxysql_usr=\"$proxysql_usr\"" > /etc/proxysql-admin.cnf
+  echo "export proxysql_pass=\"$proxysql_pass\"" >> /etc/proxysql-admin.cnf
+  echo "export proxysql_hostname=\"$proxysql_hostname\"" >> /etc/proxysql-admin.cnf
+  echo "export proxysql_port=\"$proxysql_port\"" >> /etc/proxysql-admin.cnf
+  chown proxysql.proxysql /etc/proxysql-admin.cnf
+  chmod 640 /etc/proxysql-admin.cnf
+ 
   pxc_connection_check
   echo -e "\nConfiguring ProxySQL monitoring user.."
   echo -n "Enter ProxySQL monitoring username: "
@@ -226,9 +232,9 @@ enable_proxysql(){
   if [[ -z "$check_user" ]]; then
     mysql  $DSN -e "GRANT USAGE ON *.* TO $mon_uname@'%' IDENTIFIED BY '$mon_password';" 2>/dev/null
     check_cmd $?  "Cannot create the ProxySQL monitoring user"
-    echo "update global_variables set variable_value='$mon_uname' where variable_name='mysql-monitor_username'; update global_variables set variable_value='$mon_password' where variable_name='mysql-monitor_password'; " | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
+    echo "update global_variables set variable_value='$mon_uname' where variable_name='mysql-monitor_username'; update global_variables set variable_value='$mon_password' where variable_name='mysql-monitor_password'; " | mysql -u$proxysql_usr -p$proxysql_pass -h$proxysql_hostname -P$proxysql_port 2>/dev/null
     check_cmd $?  "Cannot set the mysql-monitor variables in ProxySQL"
-    echo "LOAD MYSQL VARIABLES TO RUNTIME;SAVE MYSQL VARIABLES TO DISK;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
+    echo "LOAD MYSQL VARIABLES TO RUNTIME;SAVE MYSQL VARIABLES TO DISK;" | mysql -u$proxysql_usr -p$proxysql_pass -h$proxysql_hostname -P$proxysql_port 2>/dev/null
     echo -e "\n\nUser $mon_uname@'%' has been added with USAGE privilege\n"
   else
     echo -e "\n\nUser ${mon_uname}@'%' already present in Percona XtraDB Cluster"
@@ -236,23 +242,31 @@ enable_proxysql(){
 
   # Adding Percona XtraDB Cluster nodes to ProxySQL
   echo -e "\nAdding the Percona XtraDB Cluster server nodes to ProxySQL"
-  echo "DELETE FROM mysql_servers WHERE hostgroup_id=10" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
+  echo "DELETE FROM mysql_servers WHERE hostgroup_id=10" | mysql -u$proxysql_usr -p$proxysql_pass -h$proxysql_hostname -P$proxysql_port 2>/dev/null
   wsrep_address=(`mysql  $DSN -Bse "show status like 'wsrep_incoming_addresses'" 2>/dev/null | awk '{print $2}' | sed 's|,| |g'`)
   for i in "${wsrep_address[@]}"; do	
     ws_ip=`echo $i | cut -d':' -f1`
     ws_port=`echo $i | cut -d':' -f2`
-    echo "INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight) VALUES ('$ws_ip',10,$ws_port,1000);" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
+    echo "INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight) VALUES ('$ws_ip',10,$ws_port,1000);" | mysql -u$proxysql_usr -p$proxysql_pass -h$proxysql_hostname -P$proxysql_port 2>/dev/null
     check_cmd $? "Failed to add the Percona XtraDB Cluster server node $ws_ip:$ws_port"
   done
-  echo "LOAD MYSQL SERVERS TO RUNTIME; SAVE MYSQL SERVERS TO DISK;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
+  echo "LOAD MYSQL SERVERS TO RUNTIME; SAVE MYSQL SERVERS TO DISK;" | mysql -u$proxysql_usr -p$proxysql_pass -h$proxysql_hostname -P$proxysql_port 2>/dev/null
 
-  # Adding Percona XtraDB Cluster monitoring script
+  # Adding Percona XtraDB Cluster monitoring scripts
 
-  echo "DELETE FROM SCHEDULER WHERE ID=10;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
+  # Adding proxysql galera check scheduler
+  echo "DELETE FROM SCHEDULER WHERE ID=10;" | mysql -u$proxysql_usr -p$proxysql_pass -h$proxysql_hostname -P$proxysql_port 2>/dev/null
   check_cmd $?
-  echo "INSERT  INTO SCHEDULER (id,active,interval_ms,filename,arg1,arg2,arg3,arg4,arg5) VALUES (10,1,2000,'$PROXYSQL_GALERA_CHECK',10,10,${#wsrep_address[@]},1,'/var/lib/proxysql/galera-check.log');" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
+  echo "INSERT  INTO SCHEDULER (id,active,interval_ms,filename,arg1,arg2,arg3,arg4,arg5) VALUES (10,1,$galera_check_interval,'$PROXYSQL_GALERA_CHECK',10,10,${#wsrep_address[@]},1,'/var/lib/proxysql/galera-check.log');" | mysql -u$proxysql_usr -p$proxysql_pass -h$proxysql_hostname -P$proxysql_port 2>/dev/null
   check_cmd $? "Failed to add the Percona XtraDB Cluster monitoring scheduler in ProxySQL"
-  echo "LOAD SCHEDULER TO RUNTIME;SAVE SCHEDULER TO DISK;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
+
+  # Adding Percona XtraDB Cluster membership checking scheduler
+  echo "DELETE FROM SCHEDULER WHERE ID=11;" | mysql -u$proxysql_usr -p$proxysql_pass -h$proxysql_hostname -P$proxysql_port 2>/dev/null
+  check_cmd $?
+  echo "INSERT  INTO SCHEDULER (id,active,interval_ms,filename,arg1,arg5) VALUES (11,1,5000,'$PROXYSQL_NODE_MONITOR',10,'/var/lib/proxysql/proxysql_node_monitor.log');" | mysql -u$proxysql_usr -p$proxysql_pass -h$proxysql_hostname -P$proxysql_port 2>/dev/null
+  check_cmd $? "Failed to add the Percona XtraDB Cluster membership checking scheduler in ProxySQL"
+
+  echo "LOAD SCHEDULER TO RUNTIME;SAVE SCHEDULER TO DISK;" | mysql -u$proxysql_usr -p$proxysql_pass -h$proxysql_hostname -P$proxysql_port 2>/dev/null
 
   echo -e "\nConfiguring Percona XtraDB Cluster user to connect through ProxySQL"
   echo -n "Enter Percona XtraDB Cluster user name: "
@@ -272,135 +286,36 @@ enable_proxysql(){
   if [[ -z "$check_user" ]]; then
     mysql  $DSN -e "GRANT USAGE  ON *.* TO $pxc_uname@'%' IDENTIFIED BY '$pxc_password';" 2>/dev/null
     check_cmd $? "Cannot add Percona XtraDB Cluster user : $pxc_uname (GRANT)"
-    echo "INSERT INTO mysql_users (username,password,active,default_hostgroup) values ('$pxc_uname','$pxc_password',1,10);LOAD MYSQL USERS TO RUNTIME;SAVE MYSQL USERS FROM RUNTIME;SAVE MYSQL USERS TO DISK;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
+    echo "INSERT INTO mysql_users (username,password,active,default_hostgroup) values ('$pxc_uname','$pxc_password',1,10);LOAD MYSQL USERS TO RUNTIME;SAVE MYSQL USERS FROM RUNTIME;SAVE MYSQL USERS TO DISK;" | mysql -u$proxysql_usr -p$proxysql_pass -h$proxysql_hostname -P$proxysql_port 2>/dev/null
     check_cmd $? "Cannot add Percona XtraDB Cluster user : $pxc_uname (mysql_users update)"
     echo -e "\n\nUser $pxc_uname@'%' has been added with USAGE privilege, please make sure to grant appropriate privileges\n"
   else
     echo -e "\n\nUser ${pxc_uname}@'%' already present in Percona XtraDB Cluster"
-  fi
-
-  if [ -f $PIDFILE ]; then
-    echo -e "\n$PIDFILE pid file exists"
-    echo "Percona XtraDB Cluster ProxySQL monitoring daemon not started"
-  else
-    start_daemon  > /dev/null 2>&1 &
-    echo $! > ${PIDFILE}
-    echo -e "\nPercona XtraDB Cluster ProxySQL monitoring daemon started"
   fi
 }
 
 # Removing PXC configuration from proxysql
 disable_proxysql(){
   proxysql_connection_check
-  echo "DELETE FROM mysql_users WHERE default_hostgroup=10;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
+  echo "DELETE FROM mysql_users WHERE default_hostgroup=10;" | mysql -u$proxysql_usr -p$proxysql_pass -h$proxysql_hostname -P$proxysql_port 2>/dev/null
   check_cmd $? "Cannot delete Percona XtraDB Cluster users from ProxySQL"
-  echo "DELETE FROM mysql_servers WHERE hostgroup_id=10;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
+  echo "DELETE FROM mysql_servers WHERE hostgroup_id=10;" | mysql -u$proxysql_usr -p$proxysql_pass -h$proxysql_hostname -P$proxysql_port 2>/dev/null
   check_cmd $? "Cannot delete Percona XtraDB Cluster nodes from ProxySQL"
-  if [ -f $PIDFILE ]; then
-    PID=$(cat ${PIDFILE});
-    kill ${PID}
-    rm -rf ${PIDFILE}
-  else
-    echo "Percona XtraDB Cluster ProxySQL monitoring daemon is not running"
-  fi 
-}
-
-# Starts Percona XtraDB Cluster ProxySQL monitoring daemon
-start_daemon(){
-  while true
-  do
-    check_proxysql
-    current_hosts=(`mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port -Bse"SELECT hostname,port FROM mysql_servers WHERE status='ONLINE'" | sed 's|\t|:|g' | tr '\n' ' '`)
-    wsrep_address=(`mysql  $DSN -Bse "SHOW STATUS LIKE 'wsrep_incoming_addresses'" 2>/dev/null | awk '{print $2}' | sed 's|,| |g'`)
-    for i in "${wsrep_address[@]}"; do
-      if [[ ! " ${current_hosts[@]} " =~ " ${i} " ]]; then
-        echo "DELETE FROM mysql_servers WHERE hostgroup_id=10;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
-        for i in "${wsrep_address[@]}"; do	
-          ws_ip=`echo $i | cut -d':' -f1`
-          ws_port=`echo $i | cut -d':' -f2`
-          echo "INSERT INTO mysql_servers (hostname,hostgroup_id,port,weight) VALUES ('$ws_ip',10,$ws_port,1000);" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
-          check_cmd $? "Cannot add Percona XtraDB Cluster server node $ws_ip:$ws_port"
-        done
-        echo "LOAD MYSQL SERVERS TO RUNTIME; SAVE MYSQL SERVERS TO DISK;" | mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port 2>/dev/null
-        break
-      fi
-    done
-    sleep 5
-  done
-}
-
-# Stops Percona XtraDB Cluster ProxySQL monitoring daemon
-stop_daemon(){
-  proxysql_connection_check
-  if [ -f $PIDFILE ]; then
-    PID=$(cat ${PIDFILE});
-    kill ${PID}
-    rm -rf ${PIDFILE}
-  else
-    echo "Percona XtraDB Cluster ProxySQL monitoring daemon is not running"
-  fi 
-}
-
-# Check status of Percona XtraDB Cluster ProxySQL monitoring daemon
-
-status_daemon(){
-  proxysql_connection_check
-  if [ -f $PIDFILE ] ; then
-    PID=`cat $PIDFILE`
-    if [ -n $PID ]; then
-      if ps -p $PID > /dev/null; then
-        echo "Percona XtraDB Cluster ProxySQL monitoring daemon is running ($PID)"; 
-      else
-        echo "Percona XtraDB Cluster ProxySQL monitoring daemon is not running"; 
-      fi
-    fi
-  else
-    echo "Percona XtraDB Cluster ProxySQL monitoring daemon is not running"; 
-  fi
 }
 
 
-if [ "$enable" == 1 -o "$disable" == 1 -o "$start_daemon"  == 1 -o "$stop_daemon" == 1 -o "$status_daemon" == 1 ]; then
+
+if [ "$enable" == 1 -o "$disable" == 1 ]; then
   if [ "$enable" == 1 ];then
     enable_proxysql
     echo "ProxySQL configuration completed!"
   fi
-
   if [ "$disable" == 1 ];then  
     disable_proxysql
     echo "ProxySQL configuration removed!"
   fi
-
-  if [ "$start_daemon" == 1 ];then
-    proxysql_connection_check
-    if [ -f $PIDFILE ]; then
-      echo "$PIDFILE pid file exists"
-      echo "Percona XtraDB Cluster ProxySQL monitoring daemon not started"
-    else
-      check_proxysql
-      PXC_NODES_CHECK=`mysql -u$proxysql_usr -p$proxysql_pass $proxysql_hostname $proxysql_port -Bse"SELECT COUNT(*) FROM mysql_servers WHERE hostgroup_id=10;" 2>/dev/null`
-      if [ $PXC_NODES_CHECK -eq 0 ]; then
-        echo "Percona XtraDB Cluster is not configured in ProxySQL. Please add PXC nodes into ProxySQL before starting monitorning daemon."
-        exit 1
-      else
-        pxc_connection_check
-        start_daemon  > /dev/null 2>&1 &
-        echo $! > ${PIDFILE}
-        echo "Percona XtraDB Cluster ProxySQL monitoring daemon started"
-      fi
-    fi
-  fi
-
-  if [ "$stop_daemon" == 1 ];then
-    stop_daemon
-    echo "Percona XtraDB Cluster ProxySQL monitoring daemon stopped"
-  fi
-
-  if [ "$status_daemon" == 1 ];then
-    status_daemon
-  fi
 else
-  echo "Usage: proxysql-admin <user credentials> {enable|disable|start|stop|status}"
+  echo "Usage: proxysql-admin <user credentials> {enable|disable}"
   usage
 fi
 
